# Generated by Django 6.0.1 on 2026-01-21 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cctv", "CCTV"),
                            ("radios", "Radios"),
                            ("acs", "Access Control Systems (ACS)"),
                            ("iot", "IoT"),
                            ("iiot", "IIoT"),
                            ("servers", "Servers"),
                            ("network_security", "Network & Security"),
                            ("firewall", "Firewall"),
                            ("cyber_security", "Cyber Security"),
                            ("windows", "Windows"),
                            ("ot", "Operational Technology (OT)"),
                        ],
                        max_length=30,
                        verbose_name="System Category",
                    ),
                ),
                (
                    "notice_identifier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Notice Identifier"
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("tender", "Tender"),
                            ("award", "Award"),
                            ("opportunity", "Opportunity"),
                            ("other", "Other"),
                        ],
                        default="contract",
                        max_length=30,
                        verbose_name="Notice Type",
                    ),
                ),
                (
                    "serial_number",
                    models.IntegerField(blank=True, null=True, verbose_name="SR#"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awarded", "Awarded"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("pending", "Pending"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Published Date"
                    ),
                ),
                (
                    "organisation_name",
                    models.CharField(max_length=255, verbose_name="Organisation Name"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Title/Project"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "nationwide",
                    models.BooleanField(default=False, verbose_name="Nationwide"),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postcode"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=255, verbose_name="Region"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Contact Name"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(blank=True, verbose_name="Contact Address"),
                ),
                (
                    "contact_telephone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contact Telephone"
                    ),
                ),
                (
                    "contact_website",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Contact Website"
                    ),
                ),
                (
                    "cpv_codes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="CPV Codes"
                    ),
                ),
                (
                    "last_contact",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Contact"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="contacts_co_categor_353d20_idx"
                    ),
                    models.Index(
                        fields=["organisation_name"],
                        name="contacts_co_organis_6e0ea4_idx",
                    ),
                    models.Index(
                        fields=["status"], name="contacts_co_status_91fe2a_idx"
                    ),
                    models.Index(
                        fields=["region"], name="contacts_co_region_67c469_idx"
                    ),
                ],
            },
        ),
    ]
