# Generated by Django 6.0.1 on 2026-03-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("reports", "0005_salescallreport_bid_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdatabase",
            name="source_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synced_contacts",
                to="reports.salescallreport",
                verbose_name="Source Sales Call",
            ),
        ),
    ]
