# Generated by Django 6.0.1 on 2026-01-14 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("hot_lead", "Hot Lead"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("ongoing", "Ongoing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("color", models.CharField(default="#6c757d", max_length=7)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Project statuses",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField(blank=True, null=True)),
                ("project_name", models.CharField(max_length=500)),
                (
                    "proposal_reference",
                    models.CharField(
                        help_text="Leap Proposal Reference (e.g., LNUK-P02125038)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "client_rfq_reference",
                    models.CharField(
                        blank=True,
                        help_text="Client RFQ Reference Number",
                        max_length=255,
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        blank=True, help_text="Purchase Order Number", max_length=100
                    ),
                ),
                ("submission_deadline", models.DateField(blank=True, null=True)),
                ("estimated_po_date", models.DateField(blank=True, null=True)),
                (
                    "epc",
                    models.CharField(
                        blank=True, help_text="EPC Contractor", max_length=200
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated value in region currency",
                        max_digits=15,
                    ),
                ),
                (
                    "po_award_quarter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "success_quotient",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Success probability (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "minimum_achievement",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("contact_with", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("portal_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project owner/responsible person",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.projectstatus",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.region",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="projects.project",
                    ),
                ),
                (
                    "new_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.projectstatus",
                    ),
                ),
                (
                    "old_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.projectstatus",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project histories",
                "ordering": ["-changed_at"],
            },
        ),
    ]
