# Generated by Django 6.0.1 on 2026-01-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="actual_sales",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Actual sales/revenue achieved",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="year",
            field=models.CharField(
                blank=True, help_text="Financial year for this project", max_length=4
            ),
        ),
    ]
