# Generated by Django 6.0.1 on 2026-01-18 08:56

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_add_year_actual_sales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Document name/title", max_length=255),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("vendor_quotation", "Vendor Quotation"),
                            ("proposal", "Proposal"),
                            ("customer_document", "Customer Document"),
                            ("technical_document", "Technical Document"),
                            ("po_document", "Purchase Order"),
                            ("contract", "Contract"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the document"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload document (PDF, Excel, Word, etc.)",
                        upload_to=projects.models.document_upload_path,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference number (e.g., quotation number, proposal ref)",
                        max_length=100,
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        help_text="Vendor name (for vendor quotations)",
                        max_length=200,
                    ),
                ),
                (
                    "document_date",
                    models.DateField(blank=True, help_text="Document date", null=True),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Expiry date (for quotations)", null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated project (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
