# Generated by Django 6.0.1 on 2026-02-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="estimated_gp",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated Gross Profit",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimated_value_per_annum",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated value (SAR) per annum",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimated_value_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated value in USD",
                max_digits=15,
            ),
        ),
    ]
