# Generated by Django 6.0.1 on 2026-04-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_estimated_gp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="epc",
            new_name="customer",
        ),
        migrations.AlterField(
            model_name="project",
            name="customer",
            field=models.CharField(blank=True, help_text="Customer", max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="end_user",
            field=models.CharField(blank=True, help_text="End User", max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="project_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("procurement", "Procurement Stage"),
                    ("building", "Building Stage"),
                ],
                max_length=20,
                verbose_name="Project Stage",
            ),
        ),
    ]
