# Generated by Django 6.0.1 on 2026-04-20 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_rename_epc_add_enduser_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_label",
                    models.CharField(
                        help_text="Auto-assigned label like R00, R01, R02, ...",
                        max_length=16,
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Full snapshot of the project fields at save time"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional note about why this revision was created",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_revisions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial Proposal Revision",
                "verbose_name_plural": "Commercial Proposal Revisions",
                "ordering": ["-created_at"],
                "unique_together": {("project", "revision_label")},
            },
        ),
    ]
