# Generated by Django 6.0.1 on 2026-04-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_add_project_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("rfq", "Client RFQ"),
                    ("vendor_quotation", "Vendor Quotation"),
                    ("proposal", "Proposal"),
                    ("customer_document", "Customer Document"),
                    ("technical_document", "Technical Document"),
                    ("po_document", "Purchase Order"),
                    ("contract", "Contract"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
