# Generated by Django 6.0.6 on 2026-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_rfq_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal_reference',
            field=models.CharField(help_text='Leap Proposal Reference. Auto-generated for LNA (LNA #### - project name).', max_length=255, unique=True),
        ),
    ]
