# Generated by Django 6.0.6 on 2026-06-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_proposal_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_stage',
            field=models.CharField(blank=True, choices=[('', '-'), ('procurement', 'Procurement Stage'), ('building', 'Bidding Stage')], max_length=20, verbose_name='Project Stage'),
        ),
    ]
