# Generated by Django 6.0.6 on 2026-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_project_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('rfq', 'Client RFQ'), ('vendor_quotation', 'Vendor Quotation'), ('proposal', 'Proposal'), ('customer_document', 'Customer Document'), ('technical_document', 'Technical Document'), ('po_document', 'Purchase Order'), ('contract', 'Contract'), ('drawing', 'Drawing'), ('scope_of_work', 'Scope of Work'), ('instructions', 'Instructions'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
