# Generated by Django 6.0.6 on 2026-07-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_normalize_legacy_lna_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Pipeline priority', max_length=10),
        ),
    ]
