# Generated by Django 6.0.7 on 2026-08-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_deleted_at_project_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bom_started_deadline',
            field=models.DateField(blank=True, help_text='Planned date for BOM to start. Used to show early/late variance.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='costing_started_deadline',
            field=models.DateField(blank=True, help_text='Planned date for sales to start costing.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='finalized_deadline',
            field=models.DateField(blank=True, help_text='Planned date to finalise the sheet.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='handed_over_deadline',
            field=models.DateField(blank=True, help_text='Planned date to hand the BOM to sales.', null=True),
        ),
    ]
