# Generated by Django 6.0.6 on 2026-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_bom_started_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lost_comment',
            field=models.TextField(blank=True, help_text='Context for the loss. Required when the reason is Other.'),
        ),
        migrations.AddField(
            model_name='project',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('price', 'Price — we were too expensive'), ('competitor', 'Lost to competitor'), ('cancelled', 'Client cancelled — project shelved'), ('budget', 'Budget — client could not fund it'), ('timeline', 'Timeline — could not meet required dates'), ('technical', 'Technical — solution did not meet requirements'), ('no_decision', 'No decision — client went quiet'), ('no_bid', 'Did not bid — we chose not to pursue'), ('other', 'Other (comment required)')], help_text='Why the opportunity was lost. Required once the status is Lost.', max_length=20),
        ),
    ]
