# Generated by Django 6.0.7 on 2026-08-23 13:57

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_lost_comment_project_lost_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('recipients', models.CharField(blank=True, help_text="The email's 'To' line, as-is.", max_length=1000)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True)),
                ('raw_file', models.FileField(upload_to=projects.models.pipeline_email_upload_path)),
                ('raw_filename', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the email currently shown on the pipeline entry.')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('delinked_at', models.DateTimeField(blank=True, null=True)),
                ('delinked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_emails_delinked', to=settings.AUTH_USER_MODEL)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_emails_linked', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_emails', to='projects.project')),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='source_pipeline_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to='projects.pipelineemail'),
        ),
    ]
