# Generated by Django 6.0.7 on 2026-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_pipelineemail_document_source_pipeline_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineemail',
            name='recipients',
            field=models.TextField(blank=True, help_text="The email's 'To' line, as-is."),
        ),
    ]
