# Generated by Django 6.0.7 on 2026-08-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_pipelineemail_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='dashboard_group',
            field=models.CharField(blank=True, help_text="Regions sharing the same group name are combined into one tab on the main dashboard (e.g. UK and Global both set to 'LNUK'). Leave blank for a region to get its own tab.", max_length=50),
        ),
    ]
