# Generated by Django 6.0.7 on 2026-08-25 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_pipelineemail_recipients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineemail',
            name='source_mailbox',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='MonitoredMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(help_text='The employee this mailbox belongs to. Only they can browse it.', on_delete=django.db.models.deletion.CASCADE, related_name='monitored_mailbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner__username'],
            },
        ),
    ]
