# Generated by Django 6.0.7 on 2026-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_region_dashboard_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_stage',
            field=models.CharField(blank=True, choices=[('', '-'), ('procurement', 'Procurement Stage'), ('building', 'Bidding Stage'), ('budgetary', 'Budgetary Stage')], max_length=20, verbose_name='Project Stage'),
        ),
    ]
