# Generated by Django 6.0.6 on 2026-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_project_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Site location where the work is delivered', max_length=200),
        ),
    ]
