# Generated by Django 6.0.7 on 2026-09-10 13:51

from django.db import migrations, models


def set_flag_on_existing_closed_status(apps, schema_editor):
    """Backfill: before this field existed, the dashboard's Won tile
    excluded a status by matching its name against 'Closed'. Flip the flag
    on any status that already matches that old rule so behavior for
    existing data is unchanged by this migration - the flag becomes the
    source of truth going forward, but nothing silently starts counting a
    previously-excluded status as won again.
    """
    ProjectStatus = apps.get_model('projects', 'ProjectStatus')
    ProjectStatus.objects.filter(
        name='Closed', category='won'
    ).update(excluded_from_won_tile=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_project_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='excluded_from_won_tile',
            field=models.BooleanField(default=False, help_text="Projects in this status are left out of the Sales Pipeline Dashboard's Won tile/chart/list (e.g. 'Closed' - a won deal that has already been wrapped up). Meaningful only on a status whose category is Won. Every other Won-category query - procurement access, KPIs, finance, reports, and the Commercial Pipeline list itself - still counts this status as won regardless of this flag; it affects that one dashboard display only. A dedicated field rather than matching this status by name, so renaming it here can't silently break the dashboard's exclusion."),
        ),
        migrations.RunPython(set_flag_on_existing_closed_status, noop_reverse),
    ]
