# Generated by Django 6.0.7 on 2026-09-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_pipelineemail_source_mailbox_monitoredmailbox'),
        ('projects', '0019_alter_project_project_stage'),
    ]

    operations = [
    ]
