# Generated by Django 6.0.6 on 2026-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Renumbered from 0020: #223 took that number for
        # projectstatus_excluded_from_won_tile. Django reads only this
        # list and ignores the filename, so both hanging off 0019 would
        # be two leaf nodes however they were named - this chains behind
        # it instead.
        ('projects', '0020_projectstatus_excluded_from_won_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Site location where the work is delivered', max_length=200),
        ),
    ]
