# Generated by Django 6.0.7 on 2026-09-13 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_merge_20260910_1809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredmailbox',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='The admin who assigned this mailbox.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoredmailbox',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredmailbox',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='The admin who last revoked this mailbox. Cleared on reactivation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
