# Generated by Django 6.0.6 on 2026-06-29 09:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0031_costingsheet_margin_high_costingsheet_margin_low_and_more'),
        ('projects', '0010_alter_document_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Project P.O Value — the approved contract price (from the chosen margin).', max_digits=16)),
                ('approved_margin', models.CharField(blank=True, choices=[('M1', 'M1 — Current'), ('M2', 'M2 — High'), ('M3', 'M3 — Medium'), ('M4', 'M4 — Low')], help_text='Which margin scenario (M1–M4) the P.O Value came from.', max_length=2)),
                ('kickoff_date', models.DateField(blank=True, help_text='Project kickoff meeting date — milestone dates are offset from this.', null=True)),
                ('cert_approval_gap', models.PositiveIntegerField(default=2)),
                ('invoice_gap', models.PositiveIntegerField(default=30)),
                ('payment_gap', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_finances', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='projects.project')),
                ('source_sheet', models.ForeignKey(blank=True, help_text='Costing sheet the approved margin was taken from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='costing.costingsheet')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_subrow', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice_no', models.CharField(blank=True, max_length=50)),
                ('from_kickoff_days', models.PositiveIntegerField(blank=True, help_text='Days from kickoff to this milestone (drives the dates).', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('best_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('average_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('proposed_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('submitted_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('work_cert_prep_date', models.DateField(blank=True, null=True)),
                ('work_cert_approval_date', models.DateField(blank=True, null=True)),
                ('invoice_submission_date', models.DateField(blank=True, null=True)),
                ('payment_receive_date', models.DateField(blank=True, null=True)),
                ('project_finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='finance.projectfinance')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
