# Generated by Django 6.0.6 on 2026-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfinance',
            name='estimated_end_date',
            field=models.DateField(blank=True, help_text='Estimated project completion date.', null=True),
        ),
        migrations.AddField(
            model_name='projectfinance',
            name='estimated_start_date',
            field=models.DateField(blank=True, help_text='Estimated project start date.', null=True),
        ),
    ]
