# Generated by Django 6.0.6 on 2026-07-01 13:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_projectfinance_estimated_end_date_and_more'),
        ('projects', '0011_normalize_legacy_lna_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOutflowRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('A1', 'A.1 — Scope of Supply'), ('A2', 'A.2 — Scope of Services')], max_length=2)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('po_number', models.CharField(blank=True, help_text='Procurement PO covering this outflow.', max_length=100)),
                ('date_1', models.DateField(blank=True, null=True)),
                ('date_2', models.DateField(blank=True, null=True)),
                ('date_3', models.DateField(blank=True, null=True)),
                ('date_4', models.DateField(blank=True, null=True)),
                ('date_5', models.DateField(blank=True, null=True)),
                ('date_6', models.DateField(blank=True, null=True)),
                ('pct_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pct_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pct_3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pct_4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pct_5', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pct_6', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount in SAR (net, before VAT).', max_digits=16)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='VAT in SAR (15% of amount by default; editable).', max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total in SAR (amount + VAT).', max_digits=16)),
                ('remarks', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_outflow_rows', to='projects.project')),
            ],
            options={
                'ordering': ['part', 'order', 'id'],
            },
        ),
    ]
