# Generated by Django 6.0.6 on 2026-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_cashoutflowrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmilestone',
            name='actual_payment_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmilestone',
            name='period_amounts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
