# Generated by Django 6.0.6 on 2026-09-03 12:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0005_backfill_outflow_po_numbers'),
        ('projects', '0019_project_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position within the parent. Drives the 1, 1.1, 1.2 numbering.')),
                ('activity', models.CharField(max_length=500)),
                ('weightage', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Fraction of the project this activity represents (0–1). Children of an activity must sum to 1.00.', max_digits=6)),
                ('completed_fraction', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='How much of this activity is done, 0–1.', max_digits=6)),
                ('completion_date', models.DateField(blank=True, help_text='Date the activity was actually achieved.', null=True)),
                ('invoice_prerequisite', models.TextField(blank=True, help_text='The document needed before this can be invoiced — delivery note, transmittal, completion report.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pmo.projectmilestone')),
                ('payment_milestone', models.ForeignKey(blank=True, help_text='The billing row this activity invoices against, if any. Where set, cash-in is read from finance rather than retyped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_milestones', to='finance.paymentmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_fraction', models.DecimalField(decimal_places=4, max_digits=6)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_updates', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='pmo.projectmilestone')),
            ],
            options={
                'verbose_name_plural': 'Milestone progress entries',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['project', 'order'], name='pmo_project_project_bf1d85_idx'),
        ),
    ]
