# Generated by Django 6.0.7 on 2026-09-14 07:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='weightage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Fraction of the project this activity represents (0–1). The activities that carry weight sum to 1.00 across the project — either the top-level rows, or their children where the parent is left blank.', max_digits=6),
        ),
    ]
