# Generated by Django 6.0.7 on 2026-09-14 09:47

import django.db.models.deletion
import pmo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0002_alter_projectmilestone_weightage'),
        ('projects', '0021_project_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='responsible_party',
            field=models.CharField(blank=True, help_text='Whose court this activity is in right now — e.g. "Client", "LNA", "MASCO". Free text to match how delivery actually names the parties involved, project to project.', max_length=100),
        ),
        migrations.CreateModel(
            name='CommunicationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.JSONField(default=pmo.models.default_communication_columns)),
                ('rows', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_matrix', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibilityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.JSONField(default=pmo.models.default_responsibility_columns)),
                ('rows', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_matrix', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
