# Generated by Django 6.0.7 on 2026-09-15 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_monthlylatenessreport'),
        ('pmo', '0003_projectmilestone_responsible_party_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="This assignment's working title, if different from the employee's HR designation.", max_length=255)),
                ('start_contract_date', models.DateField(blank=True, null=True)),
                ('end_contract_date', models.DateField(blank=True, help_text='Leave blank while still on an open-ended assignment.', null=True)),
                ('engagement_type', models.CharField(blank=True, choices=[('direct', 'Direct'), ('subcontract', 'Subcontract'), ('agency', 'Agency')], max_length=20)),
                ('discipline', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('technical', 'Technical')], max_length=20)),
                ('employment_level', models.CharField(blank=True, choices=[('entry', 'Entry-Level'), ('mid_senior', 'Mid-Senior Level'), ('senior', 'Senior Level')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_resources_added', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(help_text='Name, ID number and active/inactive status all come from this record.', on_delete=django.db.models.deletion.CASCADE, related_name='manpower_resource', to='hr.employee')),
            ],
            options={
                'ordering': ['employee__full_name'],
            },
        ),
    ]
