# Generated by Django 6.0.7 on 2026-09-15 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0004_manpowerresource'),
        ('projects', '0022_merge_20260914_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('owner', models.CharField(blank=True, help_text='Who owns resolving this — a client, a vendor, or Leap itself (e.g. "Aramco", "MASCO", "LEAP").', max_length=255)),
                ('estimated_resolution_date', models.DateField(blank=True, null=True)),
                ('escalation_needed', models.BooleanField(default=False)),
                ('impact', models.TextField(blank=True)),
                ('actions', models.TextField(blank=True, help_text='What is being done about it.')),
                ('date_identified', models.DateField(help_text='Drives which month this issue is filed/exported under.')),
                ('actual_resolution_date', models.DateField(blank=True, help_text='Left blank while still open.', null=True)),
                ('final_resolution', models.TextField(blank=True, verbose_name='Final Resolution & Follow-on Actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
            ],
            options={
                'ordering': ['-date_identified', '-pk'],
            },
        ),
    ]
