# Generated by Django 6.0.7 on 2026-09-29 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0005_projectissue'),
        ('projects', '0022_merge_20260914_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultLossEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(blank=True, max_length=255)),
                ('lna_ref', models.CharField(blank=True, help_text="Pre-filled from the project's own reference when a project is picked, but editable - a project can carry several systems, each with its own ref.", max_length=100, verbose_name='LNA Ref#')),
                ('po_number', models.CharField(blank=True, max_length=100, verbose_name='PO#')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('delivery_time_impact', models.BooleanField(default=False)),
                ('delay_days', models.PositiveIntegerField(default=0, verbose_name='Duration of Delay (days)')),
                ('cost_impact', models.BooleanField(default=False)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Blank means not yet estimated; 0 means confirmed no cost.', max_digits=14, null=True, verbose_name='Amount of Cost (SAR)')),
                ('change_order_required', models.BooleanField(default=False)),
                ('root_causes', models.TextField(blank=True, verbose_name='Root Causes/Faults')),
                ('deviation_category', models.CharField(blank=True, choices=[('major', 'Major'), ('moderate', 'Moderate'), ('minor', 'Minor')], max_length=10)),
                ('responsibility_departments', models.CharField(blank=True, max_length=500, verbose_name='Responsibility (Departments)')),
                ('corrective_action', models.TextField(blank=True, help_text='Action to reduce repetitive faults & losses in future.', verbose_name='Corrective Action')),
                ('corrective_action_by', models.CharField(blank=True, max_length=255, verbose_name='Corrective Action By (Departments)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('closed_on', models.DateField(blank=True, help_text='Left blank while still open.', null=True)),
                ('latest_update', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_fault_loss_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_loss_entries', to='projects.project')),
            ],
            options={
                'verbose_name': 'Fault & Loss Entry',
                'verbose_name_plural': 'Faults & Losses',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
