# Generated by Django 6.0.7 on 2026-09-27 15:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0005_projectissue'),
        ('projects', '0022_merge_20260914_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstYearMaintenanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'A — Manpower Cost (Monthly / Recurring)'), ('B', 'B — Manpower Cost (One Time)'), ('C', 'C — Vehicle / Consumables / Support (Monthly)'), ('D', 'D — Tools / Equipment (One Time)')], max_length=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=255, verbose_name='Description (Role / Item)')),
                ('nature_of_expense', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount (Rate)')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_year_maintenance_lines', to='projects.project')),
            ],
            options={
                'ordering': ['section', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GradeStructureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('EX', 'EX — Executive / Management'), ('A', 'A — Administration / Support'), ('E', 'E — Engineering / Technical Professional'), ('T', 'T — Technician / Skilled Trade'), ('O', 'O — Operator / General Labour')], max_length=2)),
                ('grade_code', models.CharField(help_text='e.g. EX-1, A-1, E-3', max_length=20)),
                ('discipline', models.CharField(blank=True, max_length=100)),
                ('typical_designation', models.CharField(blank=True, max_length=255)),
                ('criteria', models.TextField(blank=True, verbose_name='Criteria / Eligibility')),
                ('headcount', models.PositiveIntegerField(default=0, verbose_name='Manpower')),
                ('indicative_monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Indicative Monthly Salary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_structure_lines', to='projects.project')),
            ],
            options={
                'ordering': ['category', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ManpowerCostingHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_type', models.CharField(blank=True, help_text='e.g. "1 Year", "Call-off"', max_length=100)),
                ('po_value', models.DecimalField(blank=True, decimal_places=2, help_text="The client PO's own stated value — distinct from the pipeline's Project.estimated_value.", max_digits=15, null=True)),
                ('currency_override', models.CharField(blank=True, help_text='Overrides the project region currency if this bid is priced differently.', max_length=3)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='VAT %')),
                ('profit_margin_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Blank = Proposed Contract Value defaults to cost, zero profit shown.', max_digits=5, null=True, verbose_name='Target Profit Margin %')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_costing_header', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
