# Generated by Django 6.0.7 on 2026-09-28 09:39, hand-edited to preserve data:
# headcount used to live directly on GradeStructureLine; it now lives on the
# new DesignationManpowerLine roster instead (GradeStructureLine.headcount
# became a computed property, summed from matching designation rows). Every
# existing grade line with a headcount gets one designation row created for
# it here, before the old column is dropped, so no existing headcount data
# is lost in the switch.
import django.db.models.deletion
from django.db import migrations, models


def copy_headcount_to_designations(apps, schema_editor):
    GradeStructureLine = apps.get_model('pmo', 'GradeStructureLine')
    DesignationManpowerLine = apps.get_model('pmo', 'DesignationManpowerLine')
    for line in GradeStructureLine.objects.all():
        if not line.headcount:
            continue
        DesignationManpowerLine.objects.create(
            project_id=line.project_id,
            order=line.order,
            designation=line.typical_designation or line.grade_code,
            category=line.category,
            grade_code=line.grade_code,
            discipline=line.discipline,
            headcount=line.headcount,
            monthly_salary=line.indicative_monthly_salary,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0006_firstyearmaintenanceline_gradestructureline_and_more'),
        ('projects', '0022_merge_20260914_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationManpowerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('category', models.CharField(choices=[('EX', 'EX — Executive / Management'), ('A', 'A — Administration / Support'), ('E', 'E — Engineering / Technical Professional'), ('T', 'T — Technician / Skilled Trade'), ('O', 'O — Operator / General Labour')], max_length=2)),
                ('grade_code', models.CharField(help_text='e.g. EX-1, A-1, E-3', max_length=20, verbose_name='Grade')),
                ('discipline', models.CharField(blank=True, max_length=100)),
                ('headcount', models.PositiveIntegerField(default=0, verbose_name='Manpower')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monthly Salary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_manpower_lines', to='projects.project')),
            ],
            options={
                'ordering': ['category', 'grade_code', 'order', 'pk'],
            },
        ),
        migrations.RunPython(copy_headcount_to_designations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='gradestructureline',
            name='headcount',
        ),
        migrations.AlterField(
            model_name='gradestructureline',
            name='indicative_monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='A reference salary for this grade — the real cost below is summed from its Designation-wise Manpower rows, not this figure.', max_digits=15, verbose_name='Indicative Monthly Salary'),
        ),
    ]
