# Generated by Django 6.0.7 on 2026-09-30 12:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0007_remove_gradestructureline_headcount_and_more'),
        ('projects', '0022_merge_20260914_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designationmanpowerline',
            name='nationality',
            field=models.CharField(choices=[('expat', 'Expat'), ('saudi', 'Saudi')], default='expat', help_text='Drives which statutory add-ons apply — see the Additional Cost breakdown.', max_length=10),
        ),
        migrations.CreateModel(
            name='EmploymentCostAssumptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overhead_pct', models.DecimalField(decimal_places=2, default=Decimal('12'), help_text='Accommodation / transport / IT / PPE, applied as a flat % of salary.', max_digits=5, verbose_name='Overhead %')),
                ('iqama_annual', models.DecimalField(decimal_places=2, default=Decimal('10350'), help_text='Expat only.', max_digits=15, verbose_name='Residence Permit (Iqama) — Annual (SAR)')),
                ('medical_annual', models.DecimalField(decimal_places=2, default=Decimal('2500'), help_text='Everyone.', max_digits=15, verbose_name='Medical Insurance — Annual (SAR)')),
                ('ticket_annual', models.DecimalField(decimal_places=2, default=Decimal('2500'), help_text='Expat only.', max_digits=15, verbose_name='Air Ticket — Annual (SAR)')),
                ('esb_pct', models.DecimalField(decimal_places=2, default=Decimal('8.33'), help_text='% of monthly salary, accrued — everyone.', max_digits=5, verbose_name='ESB (End of Service) %')),
                ('gosi_expat_pct', models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Occupational hazard only.', max_digits=5, verbose_name='GOSI — Expat %')),
                ('gosi_saudi_pct', models.DecimalField(decimal_places=2, default=Decimal('11.75'), help_text="Employer's share.", max_digits=5, verbose_name='GOSI — Saudi %')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_cost_assumptions', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
