# Generated by Django 6.0.6 on 2026-09-13 12:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0043_alter_costinglineitem_unit'),
        ('hr', '0054_monthlylatenessreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('overhead_pct', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Applied to salary + benefits.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Overhead %')),
                ('profit_pct', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Applied to salary + benefits, not to salary + overhead.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Profit %')),
                ('billable_months', models.DecimalField(decimal_places=2, default=Decimal('12'), help_text='Months a year actually invoiced. Below 12 recovers the yearly cost over fewer invoices.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hours_per_month', models.DecimalField(decimal_places=2, default=Decimal('176'), help_text='Billable hours in a month. 176 = 22 working days x 8h.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('working_days_per_month', models.DecimalField(decimal_places=2, default=Decimal('22'), help_text='Used for the daily cost. Working days, not calendar days.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_default', models.BooleanField(default=False, help_text='The basis used when a sheet does not name one.')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cost bases',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManpowerCostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_reference', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basis', models.ForeignKey(blank=True, help_text='Falls back to the default basis when blank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sheets', to='manpowercost.costbasis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_cost_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManpowerCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('employee_name', models.CharField(blank=True, help_text='Snapshotted at entry. Renaming an employee later must not rewrite what a quoted sheet says it was priced on.', max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(blank=True, choices=[('saudi', 'Saudi'), ('eastern', 'Eastern'), ('other_arabs', 'Other Arabs'), ('other', 'Other')], default='', max_length=20)),
                ('location_project', models.CharField(blank=True, max_length=255)),
                ('doj', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('demobilization_date', models.DateField(blank=True, null=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gross Salary (monthly)')),
                ('iqama_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Iqama Cost (monthly)')),
                ('service_transfer_visa_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Services Transfer & Visa Fee (monthly)')),
                ('gosi_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GOSI Cost (monthly)')),
                ('vacation_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vacation Pay (monthly)')),
                ('exe_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='EXE Cost (monthly)')),
                ('eosb', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='EOSB (monthly)')),
                ('air_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Air Ticket (monthly)')),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Insurance Cost (monthly)')),
                ('project_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Project Allowance (monthly)')),
                ('ppe', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PPE (monthly)')),
                ('engineering_council_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Engineering Council Cost (monthly)')),
                ('other_expenditures', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Other Expenditures (monthly)')),
                ('employee', models.ForeignKey(blank=True, help_text='Optional: a bid can price a role before anyone is hired.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_cost_lines', to='hr.employee')),
                ('position', models.ForeignKey(blank=True, help_text='The role, from the shared A.4 resource catalogue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_cost_lines', to='costing.resourcecatalogueitem')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manpowercost.manpowercostsheet')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ChargeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, choices=[('saudi', 'Saudi'), ('eastern', 'Eastern'), ('other_arabs', 'Other Arabs'), ('other', 'Other')], default='', max_length=20)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, help_text='Fully burdened monthly cost this rate is built from.', max_digits=12)),
                ('manual_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Overrides the derived rate. Leave blank to follow cost.', max_digits=12, null=True, verbose_name='Manual hourly rate')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rates', to='costing.resourcecatalogueitem')),
                ('basis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_rates', to='manpowercost.costbasis')),
            ],
            options={
                'ordering': ['position__order', 'position__name', 'classification'],
                'constraints': [models.UniqueConstraint(fields=('position', 'classification', 'basis'), name='unique_charge_rate_per_position_class_basis')],
            },
        ),
        migrations.AddIndex(
            model_name='manpowercostsheet',
            index=models.Index(fields=['title'], name='manpowercos_title_e91b13_idx'),
        ),
        migrations.AddIndex(
            model_name='manpowercostsheet',
            index=models.Index(fields=['project_reference'], name='manpowercos_project_b86561_idx'),
        ),
    ]
