# Generated by Django 6.0.6 on 2026-09-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpowercost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowercostline',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Basic Salary (monthly)'),
        ),
        migrations.AddField(
            model_name='manpowercostline',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowercostline',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Housing Allowance (monthly)'),
        ),
        migrations.AddField(
            model_name='manpowercostline',
            name='re_entry_visa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Re-entry Visa (monthly)'),
        ),
        migrations.AddField(
            model_name='manpowercostline',
            name='saudization_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saudization / Nitaqat levy. 12,000 a year per expatriate head in the source workbook — around 16% of its benefits bill, so leaving it out understates cost materially.', max_digits=12, verbose_name='Saudization (monthly)'),
        ),
        migrations.AddField(
            model_name='manpowercostline',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Transport Allowance (monthly)'),
        ),
    ]
