# Generated by Django 6.0.1 on 2026-03-02 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iqama_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Iqama/Passport No."
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Designation"
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Qualification"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "joining_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Joining Date"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nationality"
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[("single", "Single"), ("married", "Married")],
                        max_length=20,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=5,
                        verbose_name="Blood Group",
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Personal Email"
                    ),
                ),
                (
                    "documents_link",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Documents Link"
                    ),
                ),
                (
                    "deployment",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Deployment"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("permanent", "Permanent"),
                            ("yearly", "Yearly"),
                            ("ajeer", "AJEER"),
                        ],
                        max_length=20,
                        verbose_name="Contract Type",
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Work Email"
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Mobile Number"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="hr_employee_full_na_bb6b90_idx"
                    ),
                    models.Index(
                        fields=["nationality"], name="hr_employee_nationa_318651_idx"
                    ),
                    models.Index(
                        fields=["deployment"], name="hr_employee_deploym_96f169_idx"
                    ),
                    models.Index(
                        fields=["contract_type"], name="hr_employee_contrac_892ad2_idx"
                    ),
                ],
            },
        ),
    ]
