# Generated by Django 6.0.1 on 2026-03-02 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(max_length=255, verbose_name="Asset Name"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Asset Type"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Serial No."
                    ),
                ),
                (
                    "specifications",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Specifications"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Invoice Number"
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Employee Name"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Department"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Designation"
                    ),
                ),
                (
                    "handover_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Handover Date"
                    ),
                ),
                (
                    "handover_by",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Handover By"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[("new", "New"), ("used", "Used")],
                        max_length=20,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "return_date",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Return Date"
                    ),
                ),
                (
                    "return_to",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Return To"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="QTY"),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Purchase Date"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price (SAR)",
                    ),
                ),
                (
                    "planned_life",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Planned Asset Life"
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(default=False, verbose_name="In Stock?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["asset_name"],
                "indexes": [
                    models.Index(
                        fields=["asset_name"], name="hr_asset_asset_n_a9ad98_idx"
                    ),
                    models.Index(
                        fields=["asset_type"], name="hr_asset_asset_t_3819b8_idx"
                    ),
                    models.Index(
                        fields=["employee_name"], name="hr_asset_employe_04aab1_idx"
                    ),
                    models.Index(
                        fields=["serial_number"], name="hr_asset_serial__9be7e3_idx"
                    ),
                ],
            },
        ),
    ]
