# Generated by Django 6.0.1 on 2026-04-01 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_asset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(max_length=100, verbose_name="Plate Number"),
                ),
                (
                    "plate_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Plate Type"
                    ),
                ),
                (
                    "sequence_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Sequence Number"
                    ),
                ),
                (
                    "chassis_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Chassis Number"
                    ),
                ),
                (
                    "vehicle_maker",
                    models.CharField(max_length=100, verbose_name="Vehicle Maker"),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vehicle Model"
                    ),
                ),
                (
                    "model_year",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Model Year"
                    ),
                ),
                (
                    "major_color",
                    models.CharField(blank=True, max_length=50, verbose_name="Color"),
                ),
                (
                    "body_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Body Type"
                    ),
                ),
                (
                    "vehicle_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("sold", "Sold"),
                        ],
                        default="valid",
                        max_length=20,
                        verbose_name="Vehicle Status",
                    ),
                ),
                (
                    "mvpi_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expired", "Expired"),
                            ("not_exist", "Not Exist"),
                        ],
                        default="valid",
                        max_length=20,
                        verbose_name="MVPI Status",
                    ),
                ),
                (
                    "insurance_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expired", "Expired"),
                            ("not_exist", "Not Exist"),
                        ],
                        default="valid",
                        max_length=20,
                        verbose_name="Insurance Status",
                    ),
                ),
                (
                    "restriction_status",
                    models.CharField(
                        choices=[
                            ("unrestricted", "Unrestricted"),
                            ("restricted", "Restricted"),
                        ],
                        default="unrestricted",
                        max_length=20,
                        verbose_name="Restriction Status",
                    ),
                ),
                (
                    "ownership_date",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ownership Date"
                    ),
                ),
                (
                    "license_expiry",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="License Expiry Date"
                    ),
                ),
                (
                    "license_issue_date",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="License Issue Date"
                    ),
                ),
                (
                    "inspection_expiry",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Inspection Expiry"
                    ),
                ),
                (
                    "driver_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Driver ID"
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Driver Name"
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Branch"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "ordering": ["plate_number"],
            },
        ),
    ]
