# Generated by Django 6.0.1 on 2026-04-12 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_add_vehicle_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("joining_letter", "Joining Letter"),
                            ("asset_handover", "Asset Handover"),
                            ("leave_form", "Leave Form"),
                            ("contract", "Contract"),
                            ("iqama", "Iqama / ID Copy"),
                            ("passport", "Passport Copy"),
                            ("visa", "Visa"),
                            ("certificate", "Certificate"),
                            ("warning_letter", "Warning Letter"),
                            ("termination", "Termination Letter"),
                            ("salary_slip", "Salary Slip"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Document Title"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="employee_documents/%Y/%m/", verbose_name="File"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_employee_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Document",
                "verbose_name_plural": "Employee Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
