# Generated by Django 6.0.1 on 2026-05-04 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_add_employee_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateField(verbose_name="Handover Date")),
                (
                    "condition_out",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("damaged", "Damaged"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Condition at Handover",
                    ),
                ),
                (
                    "handover_form",
                    models.FileField(
                        blank=True,
                        help_text="Optional: scanned handover acknowledgement or photo of asset condition.",
                        null=True,
                        upload_to="hr/asset_handovers/",
                        verbose_name="Signed Handover Form",
                    ),
                ),
                (
                    "issue_notes",
                    models.TextField(blank=True, verbose_name="Issue Notes"),
                ),
                (
                    "returned_at",
                    models.DateField(blank=True, null=True, verbose_name="Return Date"),
                ),
                (
                    "condition_in",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=20,
                        verbose_name="Condition on Return",
                    ),
                ),
                (
                    "return_notes",
                    models.TextField(blank=True, verbose_name="Return Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="hr.asset",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_assignments",
                        to="hr.employee",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_returned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("returned_at__isnull", True)),
                        fields=("asset",),
                        name="hr_assetassignment_one_active_per_asset",
                    )
                ],
            },
        ),
    ]
