# Generated by Django 6.0.1 on 2026-05-06 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_assetassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="iqama_expires_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Iqama Expiry Date"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="iqama_issued_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Iqama Issue Date"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="medical_insurance_expires_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Medical Insurance Expiry Date"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="medical_insurance_issued_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Medical Insurance Issue Date"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["iqama_expires_on"], name="hr_employee_iqama_e_4b82c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["medical_insurance_expires_on"],
                name="hr_employee_medical_b0368e_idx",
            ),
        ),
    ]
