# Generated by Django 6.0.1 on 2026-06-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_employee_iqama_expires_on_employee_iqama_issued_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(max_length=40, unique=True)),
                (
                    "default_annual_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "color",
                    models.CharField(
                        default="secondary",
                        help_text="Bootstrap color name for badges",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
