# Generated by Django 6.0.1 on 2026-06-11 05:45

from django.db import migrations

DEFAULTS = [
    ('Annual', 'annual', 30, True, 'primary'),
    ('Sick', 'sick', 30, True, 'warning'),
    ('Unpaid', 'unpaid', 0, False, 'secondary'),
]


def seed(apps, schema_editor):
    LeaveType = apps.get_model('hr', 'LeaveType')
    for name, code, days, paid, color in DEFAULTS:
        LeaveType.objects.get_or_create(code=code, defaults={
            'name': name, 'default_annual_days': days, 'is_paid': paid, 'color': color})


def unseed(apps, schema_editor):
    LeaveType = apps.get_model('hr', 'LeaveType')
    LeaveType.objects.filter(code__in=[d[1] for d in DEFAULTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_leaverecord'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
