# Generated by Django 6.0.1 on 2026-06-11 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_attendancerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesettings",
            name="expected_in_by",
            field=models.TimeField(
                default=datetime.time(8, 30),
                help_text="Check-ins after this time are marked Late.",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("leave", "Leave"),
                    ("holiday", "Holiday"),
                    ("weekend", "Weekend"),
                    ("late", "Late"),
                    ("wfh", "WFH"),
                ],
                default="absent",
                max_length=10,
            ),
        ),
    ]
