# Generated by Django 6.0.1 on 2026-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_attendancesettings_expected_in_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
