# Generated by Django 6.0.1 on 2026-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0015_wfhrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverecord",
            name="medical_certificate",
            field=models.FileField(
                blank=True,
                help_text="Required for leave types that mandate a medical certificate (e.g. Sick).",
                null=True,
                upload_to="leave_certificates/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="requires_medical_certificate",
            field=models.BooleanField(
                default=False,
                help_text="If set, a medical certificate must be attached when recording this leave (e.g. Sick).",
            ),
        ),
    ]
