# Generated by Django 6.0.1 on 2026-06-11 13:41

from django.db import migrations


def set_sick_requires_certificate(apps, schema_editor):
    LeaveType = apps.get_model("hr", "LeaveType")
    LeaveType.objects.filter(code="sick").update(requires_medical_certificate=True)


def unset_sick_requires_certificate(apps, schema_editor):
    LeaveType = apps.get_model("hr", "LeaveType")
    LeaveType.objects.filter(code="sick").update(requires_medical_certificate=False)


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0016_leaverecord_medical_certificate_and_more"),
    ]

    operations = [
        migrations.RunPython(set_sick_requires_certificate, unset_sick_requires_certificate),
    ]
