# Generated by Django 6.0.6 on 2026-06-23 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_sick_requires_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Registration (Istimara)'), ('insurance', 'Insurance'), ('handover', 'Handover Form'), ('inspection', 'Inspection (MVPI)'), ('other', 'Other')], default='other', max_length=30, verbose_name='Document Type')),
                ('custom_type', models.CharField(blank=True, help_text="Label used when the type is 'Other'.", max_length=100)),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('file', models.FileField(upload_to='vehicle_documents/%Y/%m/', verbose_name='File')),
                ('expiry_date', models.DateField(blank=True, help_text='Optional — e.g. registration / insurance expiry.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vehicle_docs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'verbose_name_plural': 'Vehicle Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
