# Generated by Django 6.0.6 on 2026-06-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='inactive_from',
            field=models.DateField(blank=True, help_text='Date the employee became inactive (today or earlier).', null=True, verbose_name='Inactive From'),
        ),
    ]
