# Generated by Django 6.0.6 on 2026-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_employee_inactive_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='decommission_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='asset',
            name='decommissioned_on',
            field=models.DateField(blank=True, null=True, verbose_name='Out-of-Service Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_decommissioned',
            field=models.BooleanField(default=False, help_text='Dead / no longer usable. Kept for records but never in stock.', verbose_name='Out of Service'),
        ),
    ]
