# Generated by Django 6.0.6 on 2026-07-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_asset_decommission_reason_asset_decommissioned_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('site', 'Site')], max_length=10, verbose_name='Office / Site'),
        ),
    ]
