# Generated by Django 6.0.6 on 2026-07-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_employee_work_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('wifi', 'Auto (Wi-Fi)')], default='manual', help_text='How this record was set — manual entry or the Wi-Fi attendance agent.', max_length=10),
        ),
    ]
