# Generated by Django 6.0.6 on 2026-07-12 05:52

from django.db import migrations, models

# Leave-type codes that are conditional/incidental rather than a standard
# accrued allowance — these must not count toward the top-level summary total.
CONDITIONAL_LEAVE_CODES = ['marriage', 'death', 'death_of_family_member', 'umrah', 'new_born', 'newborn']


def mark_conditional_leave_types(apps, schema_editor):
    LeaveType = apps.get_model('hr', 'LeaveType')
    LeaveType.objects.filter(code__in=CONDITIONAL_LEAVE_CODES).update(is_accumulative=False)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0022_employee_work_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="is_accumulative",
            field=models.BooleanField(
                default=True,
                help_text="Standard accrued allowances (Annual, Sick) count toward the top-level entitlement totals. Conditional/incidental leaves (Marriage, Death of Family Member, Umrah, New Born, etc.) should have this unchecked so they don't inflate the summary total — they still show in the per-type breakdown.",
            ),
        ),
        migrations.RunPython(mark_conditional_leave_types, reverse_noop),
    ]
