# Generated by Django 6.0.6 on 2026-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0025_leave_approval_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavetype",
            name="is_accumulative",
            field=models.BooleanField(
                default=True,
                help_text="The standard accrued allowance (Annual) counts toward the top-level entitlement totals. Conditional/incidental leaves (Sick, Marriage, Death of Family Member, Umrah, New Born, etc.) should have this unchecked so they don't inflate the summary total — they still show in the per-type breakdown.",
            ),
        ),
    ]
