# Generated by Django 6.0.6 on 2026-07-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0023_attendancerecord_source"),
        ("hr", "0027_leave_type_task2_cleanup"),
    ]

    operations = []
