# Generated by Django 6.0.6 on 2026-07-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0029_leave_dashboard_access"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeaveApprover",
        ),
    ]
