# Generated by Django 6.0.6 on 2026-07-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0032_attendance_exception_and_manager_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceexception",
            name="employee_comment",
            field=models.TextField(
                blank=True,
                help_text="Optional extra context from the employee, independent of the reason category.",
            ),
        ),
    ]
