# Generated by Django 6.0.6 on 2026-07-16 07:51
#
# Manager-hierarchy rename + expansion (dual-manager model): Employee.manager
# is split into main_manager (formal single reporting line, replaces
# `manager`) and secondary_managers (new, additive M2M). Strategy:
#
# - AttendanceException.manager -> main_manager: a clean RenameField. Same
#   type, same related_name ('attendance_exceptions_to_decide') — nothing
#   else changed, so Django's autodetector offered (and we accepted) the
#   built-in rename operation, which preserves data automatically with no
#   manual step needed.
# - Employee.manager -> main_manager: NOT offered as a clean rename by the
#   autodetector, because related_name also changes (direct_reports ->
#   main_reports) alongside the field name, so the old/new field
#   definitions no longer deconstruct to the same thing. Handled instead as
#   AddField(main_manager) + a manual RunPython data migration copying every
#   existing manager_id into main_manager_id + RemoveField(manager) — in
#   that order, so no existing demo/test data assignment is lost. The
#   RemoveField is deliberately ordered LAST (Django's autodetector put it
#   first by default; reordered by hand here).
# - secondary_managers: brand new, additive M2M — no data migration needed.

import django.db.models.deletion
from django.db import migrations, models


def copy_manager_to_main_manager(apps, schema_editor):
    Employee = apps.get_model("hr", "Employee")
    Employee.objects.filter(manager__isnull=False).update(main_manager=models.F("manager"))


def copy_main_manager_to_manager(apps, schema_editor):
    Employee = apps.get_model("hr", "Employee")
    Employee.objects.filter(main_manager__isnull=False).update(manager=models.F("main_manager"))


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0033_attendance_exception_employee_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendanceexception",
            old_name="manager",
            new_name="main_manager",
        ),
        migrations.AddField(
            model_name="employee",
            name="main_manager",
            field=models.ForeignKey(
                blank=True,
                help_text="This employee's primary/formal manager, for approval routing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_reports",
                to="hr.employee",
                verbose_name="Main Manager",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="secondary_managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional people who also have visibility/override rights over this employee's requests, without being part of the formal reporting line.",
                related_name="secondary_reports",
                to="hr.employee",
                verbose_name="Secondary Managers",
            ),
        ),
        migrations.RunPython(copy_manager_to_main_manager, copy_main_manager_to_manager),
        migrations.RemoveField(
            model_name="employee",
            name="manager",
        ),
    ]
