# Generated by Django 6.0.6 on 2026-07-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0034_rename_manager_attendanceexception_main_manager_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendanceexception",
            name="arrived_late",
        ),
    ]
