# Generated by Django 6.0.7 on 2026-07-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0035_remove_attendanceexception_arrived_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='category',
            field=models.CharField(choices=[('saudi_national_day', 'Saudi National Day'), ('eid', 'Eid'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
