# Generated by Django 6.0.6 on 2026-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0036_holiday_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="site_default_annual_days",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Override default for Site employees. Blank = same as the default above (Office).",
                max_digits=5,
                null=True,
            ),
        ),
    ]
