# Generated by Django 6.0.6 on 2026-08-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0038_leaveexceptiongrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="exceeds_balance",
            field=models.BooleanField(
                default=False,
                help_text="True if this request was held (not hard-blocked) because it exceeds the employee's effective balance — only possible for work locations where balance holding is enabled. Requires a Super Admin override to approve.",
            ),
        ),
    ]
