# Generated by Django 6.0.6 on 2026-08-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0039_leaverequest_exceeds_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="overrideaccesssettings",
            name="allow_office_balance_hold",
            field=models.BooleanField(
                default=False,
                help_text="Same as above, for Office employees. Off by default — Office keeps the plain hard block.",
            ),
        ),
        migrations.AddField(
            model_name="overrideaccesssettings",
            name="allow_site_balance_hold",
            field=models.BooleanField(
                default=True,
                help_text="Site employees who submit leave exceeding their available balance get a held, reviewable request instead of a hard block.",
            ),
        ),
    ]
