# Generated by Django 6.0.6 on 2026-08-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0040_overrideaccesssettings_allow_office_balance_hold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="logged_by_manager",
            field=models.BooleanField(
                default=False,
                help_text="True if created_by was the employee's direct main_manager at the time this request was submitted (not the employee themselves, not HR). Captured at submission time — deliberately not live-recomputed, so it stays accurate even if the employee's manager changes later.",
            ),
        ),
    ]
