# Generated by Django 6.0.1 on 2026-08-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0043_attendanceexception_revoke_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="cancel_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
