# Generated by Django 6.0.7 on 2026-08-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0042_latequery'),
        ('hr', '0044_leaverequest_cancel_fields'),
    ]

    operations = [
    ]
