# Generated by Django 6.0.7 on 2026-08-13 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0044_leaverequest_cancel_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='item_description',
            field=models.TextField(blank=True, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='asset',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Part Number'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tag_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tag Number'),
        ),
        migrations.CreateModel(
            name='AssetHandoverAuthorizerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_handover_authorizer_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.TextField(blank=True)),
                ('software_installed', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_authorization', 'Pending Authorization'), ('pending_receipt', 'Pending Employee Signature'), ('active', 'Active / Issued'), ('pending_return_receipt', 'Pending Return Acknowledgement'), ('returned', 'Returned')], default='pending_authorization', max_length=25)),
                ('issued_signature', models.ImageField(blank=True, null=True, upload_to='hr/asset_handover_signatures/issued/')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_signature', models.ImageField(blank=True, null=True, upload_to='hr/asset_handover_signatures/authorized/')),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('received_signature', models.ImageField(blank=True, null=True, upload_to='hr/asset_handover_signatures/received/')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('return_remarks', models.TextField(blank=True)),
                ('returned_signature', models.ImageField(blank=True, null=True, upload_to='hr/asset_handover_signatures/returned/')),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_received_signature', models.ImageField(blank=True, null=True, upload_to='hr/asset_handover_signatures/return_received/')),
                ('return_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='hr.asset')),
                ('authorizer', models.ForeignKey(blank=True, help_text='The Super Admin selected to authorize this handover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_handovers_to_authorize', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_handovers', to='hr.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_handovers_issued', to=settings.AUTH_USER_MODEL)),
                ('return_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_handovers_return_received', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='hr.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='hr_assethan_status_5b68f2_idx')],
            },
        ),
    ]
