# Generated by Django 6.0.7 on 2026-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0045_asset_item_description_asset_model_asset_part_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='accessories',
            field=models.TextField(blank=True, verbose_name='Accessories'),
        ),
        migrations.AddField(
            model_name='asset',
            name='software_installed',
            field=models.TextField(blank=True, verbose_name='Software Installed'),
        ),
    ]
