# Generated by Django 6.0.7 on 2026-08-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0045_merge_0042_latequery_0044_leaverequest_cancel_fields'),
        ('hr', '0046_asset_accessories_asset_software_installed'),
    ]

    operations = [
    ]
