# Generated by Django 6.0.7 on 2026-08-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0047_merge_20260817_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethandover',
            name='status',
            field=models.CharField(choices=[('pending_authorization', 'Pending Authorization'), ('pending_receipt', 'Pending Employee Signature'), ('active', 'Active / Issued'), ('pending_return_confirmation', 'Pending Employee Confirmation'), ('returned', 'Returned')], default='pending_authorization', max_length=30),
        ),
    ]
