# Generated by Django 6.0.7 on 2026-08-19 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_migrate_legacy_asset_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assethandover',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending_authorization', 'pending_receipt', 'active', 'pending_return_confirmation'))), fields=('asset',), name='hr_assethandover_one_open_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='assethandover',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending_authorization', 'pending_receipt', 'active', 'pending_return_confirmation'))), fields=('vehicle',), name='hr_assethandover_one_open_per_vehicle'),
        ),
    ]
