# Generated by Django 6.0.7 on 2026-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0050_assethandover_hr_assethandover_one_open_per_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grade'),
        ),
    ]
