# Generated by Django 6.0.7 on 2026-08-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0051_employee_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_pictures/', verbose_name='Picture'),
        ),
    ]
