# Generated by Django 6.0.7 on 2026-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0052_employee_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('joining_letter', 'Joining Letter'), ('cv', 'CV'), ('asset_handover', 'Asset Handover'), ('leave_form', 'Leave Form'), ('contract', 'Contract'), ('iqama', 'Iqama / ID Copy'), ('passport', 'Passport Copy'), ('visa', 'Visa'), ('certificate', 'Certifications'), ('warning_letter', 'Warning Letter'), ('termination', 'Termination Letter'), ('salary_slip', 'Salary Slip'), ('other', 'Other')], default='other', max_length=30, verbose_name='Document Type'),
        ),
    ]
