# Generated by Django 6.0.7 on 2026-08-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Renumbered from 0051 and repointed at 0052 so this branch and the
        # employee grade/picture branch form one chain rather than two leaves.
        # Both were cut from dev at 0050 and both claimed 0051; Django refuses
        # a tree with two leaf nodes in one app.
        ('hr', '0052_employee_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLatenessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the reported month.')),
                ('total_lates', models.PositiveIntegerField()),
                ('late_dates', models.JSONField(default=list, help_text='ISO date strings, snapshotted at generation time.')),
                ('converted_absences', models.PositiveIntegerField()),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateness_reports', to='hr.employee')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='hr_monthlyl_month_56d7c6_idx')],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
