# Generated by Django 6.0.7 on 2026-09-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0051_monthlylatenessreport'),
        ('hr', '0052_employee_picture'),
    ]

    operations = [
    ]
