# Generated by Django 6.0.7 on 2026-08-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Renumbered from 0051, and depends on the migration immediately
        # before it rather than on a shared ancestor. That distinction is the
        # whole point: Django ignores the filename number and reads only this
        # list, so two migrations both hanging off 0052 are two leaf nodes
        # however they are numbered, and it refuses to migrate at all.
        #
        # Three branches were cut from dev at 0050 and all three claimed 0051.
        # The employee grade/picture pair landed first (0051, 0052); the
        # document-upload branch takes 0053 because it is ready and this one
        # is not; this is 0054 behind it.
        ('hr', '0053_alter_employeedocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLatenessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the reported month.')),
                ('total_lates', models.PositiveIntegerField()),
                ('late_dates', models.JSONField(default=list, help_text='ISO date strings, snapshotted at generation time.')),
                ('converted_absences', models.PositiveIntegerField()),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateness_reports', to='hr.employee')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='hr_monthlyl_month_56d7c6_idx')],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
