# Generated by Django 6.0.7 on 2026-10-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_monthlylatenessreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='replacement',
            field=models.ForeignKey(blank=True, help_text='Who covers for the employee while they are on leave. Picked by the employee from Employee.replacement_candidates(); blank on requests logged on their behalf.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_replacements', to='hr.employee'),
        ),
    ]
