# Generated by Django 6.0.1 on 2026-03-17 07:36

from django.db import migrations


def create_super_admin_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.get_or_create(
        name='super_admin',
        defaults={'description': 'Full access across all regions'}
    )


def reverse_super_admin_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(name='super_admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_super_admin_role"),
    ]

    operations = [
        migrations.RunPython(create_super_admin_role, reverse_super_admin_role),
    ]
