# Generated by Django 6.0.1 on 2026-03-17 10:21

from django.db import migrations


def promote_admin(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    User = apps.get_model('accounts', 'User')
    super_admin_role = Role.objects.get(name='super_admin')
    User.objects.filter(username='admin').update(role=super_admin_role)


def reverse_promote(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    User = apps.get_model('accounts', 'User')
    admin_role = Role.objects.get(name='admin')
    User.objects.filter(username='admin').update(role=admin_role)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_create_super_admin_role_data"),
    ]

    operations = [
        migrations.RunPython(promote_admin, reverse_promote),
    ]
