# Generated by Django 6.0.1 on 2026-03-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_promote_admin_to_super_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrator"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("sales_rep", "Sales Representative"),
                    ("procurement_mgr", "Procurement Manager"),
                    ("procurement_off", "Procurement Officer"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
