# Generated by Django 6.0.1 on 2026-03-26 13:10

from django.db import migrations


def create_procurement_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.get_or_create(
        name='procurement_mgr',
        defaults={'description': 'Full access to all procurement features'}
    )
    Role.objects.get_or_create(
        name='procurement_off',
        defaults={'description': 'Full access to all procurement features'}
    )


def reverse_procurement_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(name__in=['procurement_mgr', 'procurement_off']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_procurement_roles"),
    ]

    operations = [
        migrations.RunPython(create_procurement_roles, reverse_procurement_roles),
    ]
