# Generated by Django 6.0.1 on 2026-03-26 13:16

from django.db import migrations


def promote_admin(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    User = apps.get_model('accounts', 'User')
    super_admin_role = Role.objects.get(name='super_admin')
    User.objects.filter(username='admin').update(role=super_admin_role)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_create_procurement_roles_data"),
    ]

    operations = [
        migrations.RunPython(promote_admin, noop),
    ]
