# Generated by Django 6.0.1 on 2026-04-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_password_reset_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresetrequest",
            name="new_password_hash",
        ),
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_user", "Waiting for User"),
                    ("approved", "Completed"),
                    ("rejected", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="pending_user",
                max_length=20,
            ),
        ),
    ]
