# Generated by Django 6.0.1 on 2026-04-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_new_password_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrator"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("sales_rep", "Sales Representative"),
                    ("procurement_mgr", "Procurement Manager"),
                    ("procurement_off", "Procurement Officer"),
                    ("proposal_head", "Proposal Team Head"),
                    ("proposal_rep", "Proposal Representative"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
