# Generated by Django 6.0.1 on 2026-06-16 05:25

from django.db import migrations

# Roles re-baselined to the Dev-Tracking silo. 0021 seeded these with the old
# open-module baseline (allowed=True); seed_default_permissions only fills
# MISSING rows, so we must explicitly recompute their existing rows here.
AI_ROLES = ['developer', 'ai_head', 'ai_intern', 'ai_engineer', 'ai_junior_engineer']


def silo_ai_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    RolePermission = apps.get_model('accounts', 'RolePermission')
    from accounts.permissions import (
        CAPABILITIES, DEFAULT_MODULE_ACCESS, DEFAULT_CODENAME_GRANTS)
    access_actions = {'access', 'nav'}
    for role in Role.objects.filter(name__in=AI_ROLES):
        modules_on = DEFAULT_MODULE_ACCESS.get(role.name, set())
        codenames_on = DEFAULT_CODENAME_GRANTS.get(role.name, set())
        for cap in CAPABILITIES:
            module_key = cap.codename.rsplit('.', 1)[0]
            should = (
                (cap.action in access_actions and module_key in modules_on)
                or cap.codename in codenames_on
            )
            RolePermission.objects.update_or_create(
                role=role, codename=cap.codename, defaults={'allowed': should})


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_seed_ai_team_roles"),
    ]

    operations = [
        migrations.RunPython(silo_ai_roles, migrations.RunPython.noop),
    ]
