# Generated by Django 6.0.7 on 2026-08-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_seed_timesheets_permissions'),
        ('accounts', '0028_seed_authorization_roles'),
    ]

    operations = [
    ]
