# Generated by Django 6.0.7 on 2026-09-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_seed_pm_dashboard_permissions'),
        ('accounts', '0035_grant_pcc_costing_access'),
    ]

    operations = [
    ]
