"""Writing real PO numbers onto the cash-outflow schedule.

A cash-outflow row is generated from a costing line and carries a `po_number`
finance types in by hand once procurement raises the order. That means the
schedule is only as current as somebody's memory of which PO covered which
line — and the number is the one field on the row that another part of the
system already knows for certain.

The link already exists at both ends and nothing was joining them:

    CashOutflowRow.source_ref      'line:<CostingLineItem.pk>'
    PurchaseOrderItem.source_bom_item -> CostingLineItem

So when a PO reaches a committed status, every outflow row seeded from a
costing line that PO covers can be filled in.

Three rules make this safe to run repeatedly and safe to run at all:

**Never overwrite.** Finance may have typed something the system does not know
about. A number is only ever added, never replaced — a row that already names
this PO is left completely alone, so re-running changes nothing.

**Never write a placeholder.** A PO seeded from a budget starts life with a
generated number like `DRAFT-S12-1787214550` that exists purely to satisfy the
unique constraint until somebody types the real one. Writing that onto a
financial schedule would be worse than leaving the field empty, because it
looks like an answer.

**Only committed orders.** A draft has not been ordered, so it does not yet
cover any outflow. This uses the same status rule as the budget and system
figures, so all three agree about what "ordered" means.
"""
from .models import CashOutflowRow

# Generated by po_from_budget to satisfy the unique constraint until a real
# number is entered. Never a real PO number.
PLACEHOLDER_PREFIX = 'DRAFT-'

MAX_PO_NUMBER_FIELD = CashOutflowRow._meta.get_field('po_number').max_length


def is_placeholder(po_number):
    return not po_number or po_number.startswith(PLACEHOLDER_PREFIX)


def _append(existing, po_number):
    """Add a PO number to a field that may already name others.

    A costing line can be split across several orders, so the field has to hold
    more than one. Returning None means "nothing to do" — which keeps the caller
    from writing a row it did not change.
    """
    existing = (existing or '').strip()
    if not existing:
        return po_number
    # Compared as whole entries so PO-1 is not considered present in PO-10.
    entries = [part.strip() for part in existing.split(',') if part.strip()]
    if po_number in entries:
        return None
    combined = f'{existing}, {po_number}'
    if len(combined) > MAX_PO_NUMBER_FIELD:
        # Silently truncating a PO number would produce one that does not
        # exist, which is worse than showing fewer of them.
        return None
    return combined


def fill_po_numbers(purchase_order):
    """Stamp this PO's number onto the outflow rows its items cover.

    Returns the number of rows changed. Safe to call repeatedly and from any
    path that issues a PO.
    """
    from procurement.budget_status import COMMITTED_STATUSES

    po = purchase_order
    if po.status not in COMMITTED_STATUSES:
        return 0
    if not po.project_id or is_placeholder(po.po_number):
        return 0

    line_ids = [i.source_bom_item_id for i in po.items.all() if i.source_bom_item_id]
    if not line_ids:
        return 0

    refs = {f'line:{pk}' for pk in line_ids}
    rows = CashOutflowRow.objects.filter(project_id=po.project_id, source_ref__in=refs)

    changed = 0
    for row in rows:
        updated = _append(row.po_number, po.po_number)
        if updated is None:
            continue
        row.po_number = updated
        row.save(update_fields=['po_number', 'updated_at'])
        changed += 1
    return changed


def backfill(purchase_orders=None):
    """Fill the rows for orders that were already committed before this existed.

    Separated from fill_po_numbers so it can be driven from a migration, which
    is the only route to production for a one-off like this — the web service
    has no shell.
    """
    from procurement.budget_status import COMMITTED_STATUSES
    from procurement.models import PurchaseOrder

    if purchase_orders is None:
        purchase_orders = (PurchaseOrder.objects
                           .filter(status__in=COMMITTED_STATUSES,
                                   project__isnull=False)
                           .prefetch_related('items'))
    return sum(fill_po_numbers(po) for po in purchase_orders)
