# Generated by Django 6.0.1 on 2026-03-04 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManpowerSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "project_reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Project Reference"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manpower_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManpowerLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="Employee Name"),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Department"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Classification of Staff",
                    ),
                ),
                (
                    "location_project",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Location/Project"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Designation"
                    ),
                ),
                (
                    "doj",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Joining"
                    ),
                ),
                (
                    "demobilization_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Demobilization Date"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "budget_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Budget Cost",
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Gross Salary",
                    ),
                ),
                (
                    "iqama_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Iqama Cost",
                    ),
                ),
                (
                    "service_transfer_visa_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Services Transfer & Visa Fee",
                    ),
                ),
                (
                    "gosi_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="GOSI Cost",
                    ),
                ),
                (
                    "vacation_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Vacation Pay",
                    ),
                ),
                (
                    "exe_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="EXE Cost",
                    ),
                ),
                (
                    "eosb",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="EOSB"
                    ),
                ),
                (
                    "air_ticket",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Air Ticket",
                    ),
                ),
                (
                    "insurance_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Insurance Cost",
                    ),
                ),
                (
                    "project_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Project Allowance",
                    ),
                ),
                (
                    "ppe",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="PPE"
                    ),
                ),
                (
                    "engineering_council_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Engineering Council Cost",
                    ),
                ),
                (
                    "other_expenditures",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Other Expenditures",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="manpower.manpowersheet",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="manpowersheet",
            index=models.Index(fields=["title"], name="manpower_ma_title_11b253_idx"),
        ),
        migrations.AddIndex(
            model_name="manpowersheet",
            index=models.Index(
                fields=["project_reference"], name="manpower_ma_project_cfbf27_idx"
            ),
        ),
    ]
