# Generated by Django 6.0.1 on 2026-03-16 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_project_estimated_gp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalBoilerplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("covering_letter", "Covering Letter"),
                            ("executive_summary", "Executive Summary"),
                            ("company_overview", "Company Overview"),
                            (
                                "understanding_of_requirements",
                                "Understanding of Requirements",
                            ),
                            (
                                "proposed_technical_solution",
                                "Proposed Technical Solution",
                            ),
                            ("delivery_implementation", "Delivery & Implementation"),
                            ("risk_management", "Risk Management"),
                            ("service_management", "Service Management"),
                            ("data_protection", "Data Protection"),
                            ("assumptions_constraints", "Assumptions & Constraints"),
                        ],
                        max_length=40,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposal_boilerplates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["section", "name"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("proposal_reference", models.CharField(max_length=50, unique=True)),
                (
                    "document_type",
                    models.CharField(default="Technical Proposal", max_length=100),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("project_description", models.CharField(blank=True, max_length=500)),
                (
                    "region_entity",
                    models.CharField(
                        choices=[
                            ("LNUK", "United Kingdom"),
                            ("LNIRL", "Ireland"),
                            ("LNKSA", "Saudi Arabia"),
                        ],
                        default="LNUK",
                        max_length=10,
                    ),
                ),
                ("revision", models.CharField(default="A", max_length=10)),
                ("revision_date", models.DateField()),
                ("prepared_by_initials", models.CharField(max_length=10)),
                ("checked_by_initials", models.CharField(blank=True, max_length=10)),
                ("approved_by_initials", models.CharField(blank=True, max_length=10)),
                ("covering_letter", models.TextField(blank=True)),
                ("executive_summary", models.TextField(blank=True)),
                ("company_overview", models.TextField(blank=True)),
                ("understanding_of_requirements", models.TextField(blank=True)),
                ("proposed_technical_solution", models.TextField(blank=True)),
                ("delivery_implementation", models.TextField(blank=True)),
                ("risk_management", models.TextField(blank=True)),
                ("service_management", models.TextField(blank=True)),
                ("data_protection", models.TextField(blank=True)),
                ("assumptions_constraints", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("final", "Final"),
                            ("submitted", "Submitted"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EngineeringDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_type", models.CharField(max_length=100)),
                ("doc_number", models.CharField(max_length=100)),
                ("doc_title", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineering_documents",
                        to="proposals.technicalproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "doc_number"],
            },
        ),
    ]
