# Generated by Django 6.0.1 on 2026-04-19 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_rename_epc_add_enduser_stage"),
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrequalificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pqd_reference", models.CharField(max_length=100, unique=True)),
                (
                    "document_type",
                    models.CharField(default="Prequalification", max_length=100),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("project_description", models.CharField(blank=True, max_length=500)),
                (
                    "region_entity",
                    models.CharField(
                        choices=[
                            ("LNUK", "United Kingdom"),
                            ("LNIRL", "Ireland"),
                            ("LNKSA", "Saudi Arabia"),
                        ],
                        default="LNKSA",
                        max_length=10,
                    ),
                ),
                ("revision", models.CharField(default="0", max_length=10)),
                ("revision_date", models.DateField()),
                ("prepared_by_initials", models.CharField(max_length=10)),
                ("checked_by_initials", models.CharField(blank=True, max_length=10)),
                ("approved_by_initials", models.CharField(blank=True, max_length=10)),
                ("company_profile", models.TextField(blank=True)),
                ("list_of_material", models.TextField(blank=True)),
                ("list_of_projects", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("final", "Final"),
                            ("submitted", "Submitted"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prequalification_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prequalification_documents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PQDAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("product_catalogues", "Product Catalogues"),
                            ("government_documents", "Valid Government Documents"),
                            ("iso_certificates", "ISO Certificates"),
                            ("qualifications", "Qualifications (CVs)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="pqd/attachments/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pqd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="proposals.prequalificationdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "order", "pk"],
            },
        ),
    ]
