# Generated by Django 6.0.1 on 2026-04-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0002_add_pqd_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="prequalificationdocument",
            name="government_documents",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="prequalificationdocument",
            name="iso_certificates",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="prequalificationdocument",
            name="product_catalogues",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="prequalificationdocument",
            name="qualifications",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pqdattachment",
            name="section",
            field=models.CharField(
                choices=[
                    ("company_profile", "Company Profile"),
                    ("list_of_material", "List of Material"),
                    ("product_catalogues", "Product Catalogues"),
                    ("government_documents", "Valid Government Documents"),
                    ("iso_certificates", "ISO Certificates"),
                    ("qualifications", "Qualifications (CVs)"),
                    ("list_of_projects", "List of Complete Projects"),
                ],
                max_length=30,
            ),
        ),
    ]
