# Generated by Django 6.0.6 on 2026-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_pqd_all_sections_have_text_and_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prequalificationdocument',
            name='region_entity',
            field=models.CharField(choices=[('LNUK', 'Global'), ('LNKSA', 'Arabia')], default='LNKSA', max_length=10),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='region_entity',
            field=models.CharField(choices=[('LNUK', 'Global'), ('LNKSA', 'Arabia')], default='LNUK', max_length=10),
        ),
    ]
