# Generated by Django 6.0.6 on 2026-06-30 13:53

import django.db.models.deletion
import proposals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_normalize_legacy_lna_references'),
        ('proposals', '0006_seed_headings_and_migrate_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrequalLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pdf', models.FileField(blank=True, help_text='The PDF for this heading (e.g. ISO 9001 certificate).', null=True, upload_to=proposals.models.prequal_library_upload_path)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'heading'],
            },
        ),
        migrations.CreateModel(
            name='PrequalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prequal_submissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prequal_submissions', to='projects.project')),
                ('selected_items', models.ManyToManyField(blank=True, related_name='submissions', to='proposals.prequallibraryitem')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
