# Generated by Django 6.0.6 on 2026-07-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_seed_prequal_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='prequalsubmission',
            name='block_date',
            field=models.CharField(blank=True, help_text='Date in PREPARED/REVIEWED/APPROVED blocks, e.g. JUN-2026', max_length=20),
        ),
        migrations.AddField(
            model_name='prequalsubmission',
            name='cover_date',
            field=models.CharField(blank=True, help_text='DATE band value', max_length=30),
        ),
        migrations.AddField(
            model_name='prequalsubmission',
            name='dep_1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Project Dep 1'),
        ),
        migrations.AddField(
            model_name='prequalsubmission',
            name='dep_2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Project Dep 2'),
        ),
        migrations.AddField(
            model_name='prequalsubmission',
            name='dep_3',
            field=models.CharField(blank=True, max_length=10, verbose_name='Project Dep 3'),
        ),
        migrations.AddField(
            model_name='prequalsubmission',
            name='description_month',
            field=models.CharField(blank=True, help_text='e.g. JUN/2026', max_length=20),
        ),
        migrations.AddField(
            model_name='prequalsubmission',
            name='description_text',
            field=models.CharField(blank=True, help_text='e.g. 2870 TECHNICAL PROPOSAL', max_length=100),
        ),
        migrations.AddField(
            model_name='prequalsubmission',
            name='report_no',
            field=models.CharField(blank=True, help_text='REPORT NO.', max_length=50),
        ),
        migrations.AddField(
            model_name='prequalsubmission',
            name='revision',
            field=models.CharField(blank=True, help_text='REV, e.g. A', max_length=10),
        ),
    ]
