# Generated by Django 6.0.7 on 2026-08-16 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_prequalsubmission_block_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionHeadingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ai', 'AI'), ('telecom', 'Telecom'), ('procurement', 'Procurement')], max_length=20)),
                ('content', models.TextField(blank=True, help_text='Rich HTML content, same format as a proposal section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_templates', to='proposals.sectionheading')),
            ],
            options={
                'ordering': ['heading__order', 'department'],
                'unique_together': {('heading', 'department')},
            },
        ),
    ]
