# Generated by Django 6.0.7 on 2026-08-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_seed_dept_section_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionheadingtemplate',
            name='department',
            field=models.CharField(choices=[('ai', 'AI'), ('telecom', 'Telecom'), ('procurement', 'Security')], max_length=20),
        ),
    ]
