# Generated by Django 6.0.7 on 2026-09-07 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_seed_new_telecom_headings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalproposal',
            name='department',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('telecom', 'Telecom'), ('procurement', 'Security')], default='', help_text='Which department this proposal is for — controls whether the export-lock feature applies to it.', max_length=20),
        ),
        migrations.CreateModel(
            name='ProposalDepartmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ai', 'AI'), ('telecom', 'Telecom'), ('procurement', 'Security')], max_length=20, unique=True)),
                ('requires_client_email_to_export', models.BooleanField(default=False, help_text='If checked, a Technical Proposal in this department cannot be exported as DOCX until a client email has been linked to it.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department'],
            },
        ),
        migrations.CreateModel(
            name='ProposalLinkedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_message_id', models.CharField(max_length=255, unique=True)),
                ('mailbox', models.EmailField(help_text="The mailbox this was read from - recorded at link time so a later attachment download always uses this, never the current viewer's own.", max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('to_recipients', models.CharField(blank=True, max_length=1000)),
                ('cc_recipients', models.CharField(blank=True, max_length=1000)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_meta', models.JSONField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_emails_linked', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_emails', to='proposals.technicalproposal')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ProposalMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(help_text='The employee this mailbox belongs to. Only they can browse it.', on_delete=django.db.models.deletion.CASCADE, related_name='proposal_mailbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner__username'],
            },
        ),
    ]
