# Generated by Django 6.0.7 on 2026-09-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_technicalproposal_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalproposal',
            name='department',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('telecom', 'Telecom'), ('procurement', 'Security'), ('other', 'Other')], default='', help_text='Which department this proposal is for — controls whether the export-lock feature applies to it.', max_length=20),
        ),
    ]
