# Generated by Django 6.0.7 on 2026-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_alter_technicalproposal_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaldepartmentfeature',
            name='department',
            field=models.CharField(choices=[('ai', 'AI'), ('telecom', 'Telecom'), ('procurement', 'Security'), ('other', 'Other')], max_length=20, unique=True),
        ),
    ]
