# Generated by Django 6.0.1 on 2026-01-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_add_annual_report_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesCallReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_date", models.DateField(verbose_name="Call Date")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("email_call", "Email/Call"),
                            ("meeting", "Meeting"),
                            ("site_visit", "Site Visit"),
                            ("presentation", "Presentation"),
                            ("follow_up", "Follow Up"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiation", "Negotiation"),
                            ("other", "Other"),
                        ],
                        default="email_call",
                        max_length=30,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("referral", "Referral"),
                            ("new_customer", "New Customer"),
                            ("existing_customer", "Existing Customer"),
                            ("cold_call", "Cold Call"),
                            ("inbound", "Inbound Inquiry"),
                            ("trade_show", "Trade Show Lead"),
                            ("online", "Online Lead"),
                            ("other", "Other"),
                        ],
                        default="direct",
                        max_length=30,
                        verbose_name="Contact Information/Type",
                    ),
                ),
                (
                    "system_category",
                    models.CharField(
                        choices=[
                            ("cctv", "CCTV"),
                            ("radios", "Radios"),
                            ("acs", "Access Control Systems (ACS)"),
                            ("iot", "IoT"),
                            ("iiot", "Industrial IoT (IIoT)"),
                            ("servers", "Servers"),
                            ("network_security", "Network & Security"),
                            ("firewall", "Firewall"),
                            ("cyber_security", "Cyber Security"),
                            ("windows", "Windows"),
                            ("ot", "Operational Technology (OT)"),
                            ("solar", "Solar"),
                            ("energy", "Energy"),
                            ("council", "Council"),
                            ("education", "Education"),
                            ("healthcare", "Healthcare"),
                            ("manufacturing", "Manufacturing"),
                            ("oil_gas", "Oil & Gas"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Systems Relates",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Company"),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=255, verbose_name="Contact Name"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mr", "Mr"),
                            ("mrs", "Mrs"),
                            ("ms", "Ms"),
                            ("dr", "Dr"),
                            ("prof", "Prof"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Title",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Role/Position"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=100, verbose_name="Phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("company_intro", "Company Introduction"),
                            ("product_demo", "Product Demo"),
                            ("requirement_gathering", "Requirement Gathering"),
                            ("proposal_discussion", "Proposal Discussion"),
                            ("pricing_negotiation", "Pricing Negotiation"),
                            ("contract_signing", "Contract Signing"),
                            ("follow_up", "Follow Up"),
                            ("relationship_building", "Relationship Building"),
                            ("technical_discussion", "Technical Discussion"),
                            ("complaint_resolution", "Complaint Resolution"),
                            ("other", "Other"),
                        ],
                        default="company_intro",
                        max_length=30,
                        verbose_name="Goal",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="Comments/Notes"),
                ),
                (
                    "next_action_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Action Date"
                    ),
                ),
                (
                    "next_action_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("send_email", "Send Email"),
                            ("make_call", "Make Call"),
                            ("schedule_meeting", "Schedule Meeting"),
                            ("send_proposal", "Send Proposal"),
                            ("follow_up", "Follow Up"),
                            ("site_visit", "Site Visit"),
                            ("demo_scheduled", "Demo Scheduled"),
                            ("waiting_response", "Waiting for Response"),
                            ("meeting_done", "Meeting Done/Feedback Received"),
                            ("closed_won", "Closed - Won"),
                            ("closed_lost", "Closed - Lost"),
                            ("on_hold", "On Hold"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Next Action Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sales_rep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_call_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sales Representative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Call Report",
                "verbose_name_plural": "Sales Call Reports",
                "ordering": ["-call_date", "-created_at"],
            },
        ),
    ]
