# Generated by Django 6.0.1 on 2026-01-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_add_sales_call_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salescallreport",
            name="system_category",
        ),
        migrations.AddField(
            model_name="salescallreport",
            name="system_categories",
            field=models.TextField(
                default="other",
                help_text="Comma-separated category codes",
                verbose_name="Systems Relates",
            ),
        ),
    ]
