# Generated by Django 6.0.1 on 2026-02-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_add_sales_call_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="salescallreport",
            name="bid_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "N/A"),
                    ("submitted", "Submitted"),
                    ("under_process", "Under Process"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                ],
                default="",
                max_length=20,
                verbose_name="Bid Status",
            ),
        ),
        migrations.AddField(
            model_name="salescallreport",
            name="estimated_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Project Estimated Value",
            ),
        ),
        migrations.AlterField(
            model_name="salescallreport",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("email_call", "Email/Call"),
                    ("meeting", "Meeting"),
                    ("site_visit", "Site Visit"),
                    ("presentation", "Presentation"),
                    ("follow_up", "Follow Up"),
                    ("proposal_sent", "Proposal Sent"),
                    ("proposal_creation", "Proposal Creation"),
                    ("negotiation", "Negotiation"),
                    ("other", "Other"),
                ],
                default="email_call",
                max_length=30,
                verbose_name="Action Type",
            ),
        ),
        migrations.AlterField(
            model_name="salescallreport",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("direct", "Direct"),
                    ("referral", "Referral"),
                    ("new_customer", "New Customer"),
                    ("existing_customer", "Existing Customer"),
                    ("cold_call", "Cold Call"),
                    ("inbound", "Inbound Inquiry"),
                    ("trade_show", "Trade Show Lead"),
                    ("online", "Online Lead"),
                    ("epc", "EPC"),
                    ("contractor", "Contractor"),
                    ("other", "Other"),
                ],
                default="direct",
                max_length=30,
                verbose_name="Contact Information/Type",
            ),
        ),
    ]
