# Generated by Django 6.0.1 on 2026-01-29 11:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_number", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "section_number"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_code", models.CharField(max_length=10, unique=True)),
                ("currency_name", models.CharField(max_length=50)),
                (
                    "rate_to_usd",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["currency_code"],
            },
        ),
        migrations.CreateModel(
            name="CostingLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=500)),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("EA", "EA"),
                            ("LOT", "LOT"),
                            ("Mtr", "Mtr"),
                            ("Roll", "Roll"),
                            ("Set", "Set"),
                            ("Pair", "Pair"),
                            ("Box", "Box"),
                            ("Pkt", "Pkt"),
                        ],
                        default="EA",
                        max_length=20,
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=255)),
                ("supplier_currency", models.CharField(default="SAR", max_length=10)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="costing.costingsection",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "item_number"],
            },
        ),
        migrations.CreateModel(
            name="CostingSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("customer_reference", models.CharField(blank=True, max_length=255)),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.4000"), max_digits=5
                    ),
                ),
                (
                    "ddp_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("output_currency", models.CharField(default="SAR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("final", "Final")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costing_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costing_sheets",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="costingsection",
            name="costing_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="costing.costingsheet",
            ),
        ),
    ]
