# Generated by Django 6.0.1 on 2026-02-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="costinglineitem",
            name="system",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
