# Generated by Django 6.0.1 on 2026-02-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0002_costinglineitem_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="costinglineitem",
            name="margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Item-specific margin. If blank, uses sheet margin.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
