# Generated by Django 6.0.1 on 2026-02-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0003_add_margin_to_lineitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costinglineitem",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="costinglineitem",
            name="supplier_currency",
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="customs",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="finances",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="installation",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="shipping",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
