# Generated by Django 6.0.1 on 2026-02-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0004_simplify_costing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="costinglineitem",
            name="supplier_currency",
            field=models.CharField(default="SAR", max_length=10),
        ),
    ]
