# Generated by Django 6.0.1 on 2026-02-09 07:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0005_add_supplier_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costingsheet",
            name="ddp_rate",
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="customs_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="finances_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="installation_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="shipping_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=5
            ),
        ),
    ]
