# Generated by Django 6.0.1 on 2026-02-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0006_update_sheet_rates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costinglineitem",
            name="customs",
        ),
        migrations.RemoveField(
            model_name="costinglineitem",
            name="finances",
        ),
        migrations.RemoveField(
            model_name="costinglineitem",
            name="installation",
        ),
        migrations.RemoveField(
            model_name="costinglineitem",
            name="shipping",
        ),
        migrations.RemoveField(
            model_name="costinglineitem",
            name="unit_cost",
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="base_unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Raw cost from supplier",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="customs_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Customs %. If blank, uses sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="finances_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Finances %. If blank, uses sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="installation_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Installation %. If blank, uses sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="shipping_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Shipping %. If blank, uses sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="costinglineitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Discount amount", max_digits=15
            ),
        ),
    ]
