# Generated by Django 6.0.1 on 2026-02-10 07:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0007_update_cost_fields_to_percentages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costinglineitem",
            name="customs_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Customs %. If blank, uses sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="costinglineitem",
            name="finances_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Finances %. If blank, uses sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="costinglineitem",
            name="installation_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Installation %. If blank, uses sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="costinglineitem",
            name="margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Item-specific margin. If blank, uses sheet margin.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="costinglineitem",
            name="shipping_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Shipping %. If blank, uses sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="customs_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="discount_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="finances_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="installation_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="margin",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("40"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="shipping_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
    ]
