# Generated by Django 6.0.1 on 2026-02-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0008_update_percentage_fields_to_whole_numbers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costinglineitem",
            name="discount",
        ),
        migrations.AddField(
            model_name="costinglineitem",
            name="discount_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discount %. If blank, uses sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
