# Generated by Django 6.0.1 on 2026-03-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0009_change_discount_to_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="conclusion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="end_user",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="exclusions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="fax",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="payment_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="telephone",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="terms_and_conditions",
            field=models.TextField(blank=True),
        ),
    ]
