# Generated by Django 6.0.1 on 2026-03-10 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "costing",
            "0010_costingsheet_conclusion_costingsheet_contact_person_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("terms_and_conditions", "Terms & Conditions"),
                            ("exclusions", "Exclusions"),
                            ("payment_terms", "Payment Terms"),
                            ("conclusion", "Conclusion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terms_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="selected_terms",
            field=models.ManyToManyField(
                blank=True, related_name="costing_sheets", to="costing.termstemplate"
            ),
        ),
    ]
