# Generated by Django 6.0.1 on 2026-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0011_termstemplate_costingsheet_selected_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costingsection",
            name="section_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
