# Generated by Django 6.0.1 on 2026-04-12 14:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0012_section_number_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="scope_of_work_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Total value for A.2 Scope of Work",
                max_digits=15,
                verbose_name="Scope of Work Total",
            ),
        ),
        migrations.CreateModel(
            name="ScopeOfWorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(default=1, verbose_name="S.No."),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=12
                    ),
                ),
                (
                    "uom",
                    models.CharField(default="LOT", max_length=50, verbose_name="UOM"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Total Price",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "costing_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_of_work_items",
                        to="costing.costingsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "serial_number"],
            },
        ),
    ]
