# Generated by Django 6.0.1 on 2026-04-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0013_add_scope_of_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsection",
            name="customs_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Section customs %. Blank = use sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsection",
            name="discount_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Section discount %. Blank = use sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsection",
            name="finances_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Section finances %. Blank = use sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsection",
            name="installation_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Section installation %. Blank = use sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsection",
            name="margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Section margin %. Blank = use sheet margin.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsection",
            name="shipping_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Section shipping %. Blank = use sheet rate.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
