# Generated by Django 6.0.1 on 2026-04-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0014_add_section_rate_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="scopeofworkitem",
            name="price_text",
            field=models.CharField(
                blank=True,
                help_text='If set, shows this text instead of the number (e.g. "Included", "TBD")',
                max_length=100,
                verbose_name="Price Text",
            ),
        ),
    ]
