# Generated by Django 6.0.1 on 2026-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0015_add_sow_price_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsection",
            name="is_optional",
            field=models.BooleanField(
                default=False,
                help_text="Mark this section as optional. Its subtotal is shown but excluded from the grand total unless the sheet setting is enabled.",
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="include_optional_in_total",
            field=models.BooleanField(
                default=False,
                help_text="If checked, optional sections are included in the grand total. Otherwise they are shown but not counted.",
            ),
        ),
    ]
