# Generated by Django 6.0.1 on 2026-04-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0016_add_optional_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostingSheetRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_label",
                    models.CharField(
                        help_text="Auto-assigned label like R00, R01, R02, ...",
                        max_length=16,
                    ),
                ),
                ("file", models.FileField(upload_to="costing/revisions/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costing_pdf_revisions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_revisions",
                        to="costing.costingsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("sheet", "revision_label")},
            },
        ),
    ]
