# Generated by Django 6.0.1 on 2026-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0017_add_costing_sheet_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheetrevision",
            name="change_details",
            field=models.JSONField(
                blank=True,
                help_text="Full list of field-level changes vs previous revision",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsheetrevision",
            name="change_summary",
            field=models.CharField(
                blank=True,
                help_text="Short one-line summary of changes vs previous revision",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="costingsheetrevision",
            name="export_format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("excel", "Excel")],
                default="pdf",
                help_text="Which export produced this revision",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="costingsheetrevision",
            name="snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Key sheet state at save time (for change tracking)",
                null=True,
            ),
        ),
    ]
