# Generated by Django 6.0.1 on 2026-04-20 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0018_revision_add_excel_snapshot_diff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostingSheetChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_team",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal"),
                            ("sales", "Sales"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("sheet", "Sheet"),
                            ("section", "Section"),
                            ("item", "Line item"),
                        ],
                        default="sheet",
                        max_length=16,
                    ),
                ),
                (
                    "scope_label",
                    models.CharField(
                        blank=True,
                        help_text='Short human description of the thing changed (e.g. "Section 2.1 — Camera")',
                        max_length=255,
                    ),
                ),
                ("field", models.CharField(blank=True, max_length=64)),
                ("before", models.TextField(blank=True)),
                ("after", models.TextField(blank=True)),
                ("is_pricing_change", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costing_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log",
                        to="costing.costingsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
