# Generated by Django 6.0.1 on 2026-04-20 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0019_add_costing_changelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="costing_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the sales team picked it up and started pricing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="costing_started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="costing_sheets_costing_started",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="finalized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="costing_sheets_finalized",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="handed_over_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the proposal team marked the BOM ready for sales",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="handed_over_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="costing_sheets_handed_over",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="handover_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="workflow_stage",
            field=models.CharField(
                choices=[
                    ("bom_in_progress", "BOM — in progress by Proposal"),
                    ("ready_for_costing", "Ready for costing (handed over to Sales)"),
                    ("costing_in_progress", "Costing — in progress by Sales"),
                    ("finalized", "Finalized"),
                ],
                default="bom_in_progress",
                max_length=24,
            ),
        ),
    ]
