# Generated by Django 6.0.1 on 2026-04-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0020_add_workflow_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="default_supplier_currency",
            field=models.CharField(
                default="SAR",
                help_text='The currency the team is entering costs in. New line items default to this currency; use the "Apply to all" action to bulk-update existing items.',
                max_length=10,
            ),
        ),
    ]
