# Generated by Django 6.0.1 on 2026-05-10 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0025_costingsheet_additional_contacts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="finance_approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When finance approved the sheet, releasing it for procurement.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="finance_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="costing_sheets_finance_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="finance_note",
            field=models.TextField(
                blank=True, help_text="Notes from the finance team."
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="finance_review_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When sales handed the sheet over to finance for budgeting.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="finance_review_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="costing_sheets_handed_to_finance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="workflow_stage",
            field=models.CharField(
                choices=[
                    ("bom_in_progress", "BOM — in progress by Proposal"),
                    ("ready_for_costing", "Ready for costing (handed over to Sales)"),
                    ("costing_in_progress", "Costing — in progress by Sales"),
                    ("finalized", "Finalized by Sales"),
                    ("finance_review", "Finance — budgeting in progress"),
                    ("finance_approved", "Finance approved — released for Procurement"),
                ],
                default="bom_in_progress",
                max_length=24,
            ),
        ),
    ]
