# Generated by Django 6.0.1 on 2026-06-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0027_seed_usd_exchange_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="enforce_stage_barriers",
            field=models.BooleanField(
                default=True,
                help_text="When set, editing is locked to the team that owns the current workflow stage (KPI mode). Pre-existing sheets are False so they keep the older lenient rules.",
            ),
        ),
    ]
