# Generated by Django 6.0.6 on 2026-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0029_grandfather_existing_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='termstemplate',
            name='usage',
            field=models.CharField(choices=[('sales', 'Sales (Costing / Quotation)'), ('procurement', 'Procurement (Purchase Order)'), ('both', 'Both')], default='both', max_length=12),
        ),
    ]
