# Generated by Django 6.0.6 on 2026-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0030_termstemplate_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingsheet',
            name='margin_high',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='M2 — high margin % scenario (finance approval comparison).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='margin_low',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='M4 — low margin % scenario.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='margin_medium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='M3 — medium margin % scenario.', max_digits=5, null=True),
        ),
    ]
