# Generated by Django 6.0.6 on 2026-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0031_costingsheet_margin_high_costingsheet_margin_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingsheet',
            name='margin_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='M5 — final/approved margin % (the one approved for the PO).', max_digits=5, null=True),
        ),
    ]
