# Generated by Django 6.0.6 on 2026-07-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0032_costingsheet_margin_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='costinglineitem',
            name='budget_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='costinglineitem',
            name='budgeted_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='scopeofworkitem',
            name='budget_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scopeofworkitem',
            name='budgeted_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
