# Generated by Django 6.0.6 on 2026-07-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0034_costinglineitem_budget_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costinglineitem',
            name='budget_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='scopeofworkitem',
            name='budget_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
