# Generated by Django 6.0.6 on 2026-07-09 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0035_costinglineitem_budget_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costingsheet',
            name='bom_started_at',
            field=models.DateTimeField(blank=True, help_text='When the proposal team started building the BOM.', null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='bom_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_sheets_bom_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='costingsheet',
            name='workflow_stage',
            field=models.CharField(choices=[('bom_not_started', 'BOM — not started'), ('bom_in_progress', 'BOM — in progress by Proposal'), ('ready_for_costing', 'Ready for costing (handed over to Sales)'), ('costing_in_progress', 'Costing — in progress by Sales'), ('finalized', 'Finalized by Sales'), ('finance_review', 'Finance — budgeting in progress'), ('finance_approved', 'Finance approved — released for Procurement')], default='bom_not_started', max_length=24),
        ),
    ]
