# Generated by Django 6.0.7 on 2026-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0036_costingsheet_bom_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorquote',
            name='source',
            field=models.CharField(choices=[('manual', 'Manually uploaded'), ('email', 'Auto-detected from email')], default='manual', help_text='Whether this was uploaded by hand or auto-attached by the vendor-email matcher.', max_length=10),
        ),
    ]
