# Generated by Django 6.0.7 on 2026-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0037_vendorquote_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorquote',
            name='source',
            field=models.CharField(choices=[('manual', 'Manually uploaded'), ('email_auto', 'Auto-matched from email'), ('email_manual', 'Manually resolved from email')], default='manual', help_text='Whether this was uploaded by hand or auto-attached by the vendor-email matcher.', max_length=20),
        ),
    ]
