# Generated by Django 6.0.6 on 2026-09-03 08:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0037_clientremark_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('default_uom', models.CharField(default='Nos', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Unticked keeps it on existing sheets but off the picker.')),
            ],
            options={
                'verbose_name': 'Resource catalogue item',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(default=1, verbose_name='S.No.')),
                ('description', models.CharField(max_length=255, verbose_name='Resource')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12)),
                ('uom', models.CharField(default='Nos', max_length=50, verbose_name='UOM')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Rate per unit')),
                ('remarks', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('catalogue_item', models.ForeignKey(blank=True, help_text='Blank for a one-off not in the catalogue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='costing.resourcecatalogueitem')),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_lines', to='costing.costingsheet')),
            ],
            options={
                'verbose_name': 'A.4 resource line',
                'ordering': ['order', 'serial_number'],
            },
        ),
    ]
