# Generated by Django 6.0.7 on 2026-08-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0037_clientremark_grid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionEmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.EmailField(help_text='The mailbox this was sent from and is read back from.', max_length=254)),
                ('graph_conversation_id', models.CharField(db_index=True, max_length=225)),
                ('client_to', models.CharField(max_length=1000)),
                ('client_cc', models.CharField(blank=True, max_length=1000)),
                ('subject', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('replied', 'Client Replied')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_thread', to='costing.costingsheetrevision')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_threads_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_message_id', models.CharField(max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('out', 'Sent by Leap'), ('in', 'Client / other')], max_length=3)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('to_recipients', models.CharField(blank=True, max_length=1000)),
                ('cc_recipients', models.CharField(blank=True, max_length=1000)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_meta', models.JSONField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='costing.revisionemailthread')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
