# Generated by Django 6.0.7 on 2026-08-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0037_clientremark_grid'),
        ('costing', '0038_alter_vendorquote_source'),
    ]

    operations = [
    ]
