# Generated by Django 6.0.6 on 2026-09-03 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0039_seed_resource_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='costingsheet',
            name='workflow_stage',
            field=models.CharField(choices=[('bom_not_started', 'BOM — not started'), ('returned_to_proposal', 'Returned to Proposal'), ('bom_in_progress', 'BOM — in progress by Proposal'), ('ready_for_costing', 'Ready for costing (handed over to Sales)'), ('costing_in_progress', 'Costing — in progress by Sales'), ('finalized', 'Finalized by Sales'), ('finance_review', 'Finance — budgeting in progress'), ('finance_approved', 'Finance approved — released for Procurement')], default='bom_not_started', max_length=24),
        ),
        migrations.CreateModel(
            name='BomReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(help_text='What the proposal team needs to add or correct.', verbose_name='What is missing')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='costing.costingsheet')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_returns_resolved', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_returns_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BOM return',
                'ordering': ['-returned_at'],
            },
        ),
    ]
