# Generated by Django 6.0.7 on 2026-09-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0039_revisionmailbox'),
        ('costing', '0040_alter_costingsheet_workflow_stage_bomreturn'),
    ]

    operations = [
    ]
