# Generated by Django 6.0.7 on 2026-09-06 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0041_merge_20260906_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revisionemailmessage',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='revisionemailthread',
            name='last_synced_at',
        ),
        migrations.AddField(
            model_name='revisionemailmessage',
            name='attached_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 6, 8, 57, 32, 877609, tzinfo=datetime.timezone.utc), help_text="When this was linked in the ERP - not the email's own timestamp."),
            preserve_default=False,
        ),
    ]
