# Generated by Django 6.0.6 on 2026-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0042_alter_revisionemailmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costinglineitem',
            name='unit',
            field=models.CharField(choices=[('EA', 'EA'), ('LOT', 'LOT'), ('Mtr', 'Mtr'), ('Roll', 'Roll'), ('Set', 'Set'), ('Pair', 'Pair'), ('Box', 'Box'), ('Pkt', 'Pkt'), ('Inc', 'Inc')], default='EA', max_length=20),
        ),
    ]
