# Generated by Django 6.0.7 on 2026-09-14 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0044_revisionmailbox_assigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costinglineitem',
            name='added_at',
            field=models.DateTimeField(blank=True, help_text='When this sub item was added, set only when added_by_procurement.', null=True),
        ),
        migrations.AddField(
            model_name='costinglineitem',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Who added this sub item, set only when added_by_procurement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costinglineitem',
            name='added_by_procurement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costinglineitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, help_text='Set only on a procurement-added sub item; points back to the budget line item it was added under.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='costing.costinglineitem'),
        ),
    ]
