# Generated by Django 6.0.7 on 2026-07-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtracking', '0003_taskstack_devtask_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtask',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='unassigned', max_length=12),
        ),
    ]
