# Generated by Django 6.0.7 on 2026-07-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtracking', '0004_alter_devtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtask',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
