# Generated by Django 6.0.6 on 2026-06-23 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('certification', 'Certification'), ('registration', 'Registration'), ('license', 'License / Permit'), ('iso', 'ISO Certificate'), ('legal', 'Legal Document'), ('financial', 'Financial Document'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=30)),
                ('custom_type', models.CharField(blank=True, help_text="Label used when the type is 'Other'.", max_length=100)),
                ('file', models.FileField(upload_to='company_documents/%Y/%m/')),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, help_text='Certificate / registration / license number.', max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_company_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Document',
                'verbose_name_plural': 'Company Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
