# Generated by Django 6.0.7 on 2026-07-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_seed_activity_codes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheetentry',
            unique_together=set(),
        ),
    ]
