# Generated by Django 6.0.7 on 2026-08-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_deleted_at_project_deleted_by_and_more'),
        ('timesheets', '0004_hrsettings_timesheetrequest_timesheetrequestack'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='project',
            field=models.ForeignKey(blank=True, help_text="If this entry is for a client project, select the project here. If it's for an internal activity code, leave this blank.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timesheet_entries', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='activity_code',
            field=models.ForeignKey(blank=True, help_text='Internal work item (e.g., Head office). Use this OR project, not both.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='timesheets.activitycode'),
        ),
    ]
