# Generated by Django 6.0.1 on 2026-06-18 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="e.g. '2026-06', '2026-Q2', '2026'", max_length=10
                    ),
                ),
                ("kpi_key", models.CharField(max_length=60)),
                (
                    "target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "manual_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Entry",
                "verbose_name_plural": "KPI Entries",
                "ordering": ["period", "kpi_key"],
                "unique_together": {("period", "kpi_key")},
            },
        ),
    ]
