# Generated by Django 6.0.7 on 2026-08-03 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0036_holiday_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('display_text', models.CharField(blank=True, help_text='What actually shows in the calendar cell.', max_length=255)),
                ('source', models.CharField(choices=[('leave', 'Leave'), ('holiday', 'Holiday'), ('weekend', 'Weekend'), ('wfh', 'WFH'), ('timesheet', 'Timesheet'), ('manual', 'Manual (HR-entered)'), ('blank', 'Blank')], default='blank', max_length=10)),
                ('auto_generated_text', models.CharField(blank=True, max_length=255)),
                ('needs_review', models.BooleanField(default=False, help_text='Set by Generate Draft when this cell looks suspicious or conflicts with another data source — HR should double check it.')),
                ('review_reason', models.CharField(blank=True, help_text="Short note on why needs_review was set, e.g. 'Same description 3+ days running' or 'Timesheet entry logged on an approved leave day'.", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_cells', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee', 'date'],
                'indexes': [models.Index(fields=['date', 'employee'], name='engineer_ca_date_cfde57_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
