# Generated by Django 6.0.7 on 2026-08-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarcell',
            name='merge_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarcell',
            name='merge_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
