# Generated by Django 6.0.1 on 2026-03-25 06:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_project_estimated_gp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_date", models.DateField(verbose_name="PO Date")),
                (
                    "po_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="PO S. No."
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(
                        choices=[
                            ("projects", "Projects"),
                            ("operations", "Operations"),
                            ("maintenance", "Maintenance"),
                            ("it", "IT"),
                            ("other", "Other"),
                        ],
                        default="projects",
                        max_length=30,
                        verbose_name="Cost Center",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("acknowledged", "Acknowledged"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(max_length=255, verbose_name="Vendor"),
                ),
                (
                    "vendor_contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Contact Person"
                    ),
                ),
                (
                    "vendor_contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Vendor Contact Email"
                    ),
                ),
                (
                    "vendor_contact_tel",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contact Tel"
                    ),
                ),
                (
                    "po_issued_by",
                    models.CharField(max_length=255, verbose_name="PO Issued By"),
                ),
                (
                    "issuer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Issuer Contact Email"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Project Name"
                    ),
                ),
                (
                    "end_user",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="End User"
                    ),
                ),
                (
                    "mr_item_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="MR / Item No."
                    ),
                ),
                (
                    "delivery_incoterms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DDP", "DDP - Delivered Duty Paid"),
                            ("DAP", "DAP - Delivered at Place"),
                            ("EXW", "EXW - Ex Works"),
                            ("FOB", "FOB - Free on Board"),
                            ("CIF", "CIF - Cost, Insurance & Freight"),
                            ("CFR", "CFR - Cost & Freight"),
                            ("FCA", "FCA - Free Carrier"),
                            ("CPT", "CPT - Carriage Paid To"),
                            ("CIP", "CIP - Carriage & Insurance Paid To"),
                            ("DAT", "DAT - Delivered at Terminal"),
                        ],
                        max_length=10,
                        verbose_name="Delivery Incoterms",
                    ),
                ),
                (
                    "delivery_location",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Delivery Location"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="e.g. 5 for 5%",
                        max_digits=5,
                        verbose_name="Discount %",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15"),
                        help_text="e.g. 15 for 15%",
                        max_digits=5,
                        verbose_name="VAT %",
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, verbose_name="Terms & Conditions"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "ordering": ["-po_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(default=1, verbose_name="S.No."),
                ),
                (
                    "make_model",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Make/Model"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Item Description / Specification"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=12,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "uom",
                    models.CharField(default="Nos", max_length=50, verbose_name="UOM"),
                ),
                (
                    "rate_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Rate/Unit (SAR)",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "serial_number"],
            },
        ),
    ]
