# Generated by Django 6.0.1 on 2026-03-25 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial_purchase_order"),
        ("projects", "0004_project_estimated_gp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcurementSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=500, verbose_name="Project Name"),
                ),
                (
                    "package_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Package Name"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_procurement_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procurement_summaries",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Summary",
                "verbose_name_plural": "Procurement Summaries",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementSummaryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(default=1, verbose_name="Sr."),
                ),
                (
                    "system_item",
                    models.CharField(max_length=500, verbose_name="System / Item"),
                ),
                (
                    "po_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="PO Number"
                    ),
                ),
                (
                    "po_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "-"),
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("acknowledged", "Acknowledged"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="PO Status",
                    ),
                ),
                (
                    "po_qty",
                    models.CharField(blank=True, max_length=100, verbose_name="PO QTY"),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Supplier"
                    ),
                ),
                (
                    "lead_time",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Lead Time"
                    ),
                ),
                (
                    "incoterm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Incoterm"
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(blank=True, verbose_name="Payment Terms"),
                ),
                (
                    "warranty",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Warranty"
                    ),
                ),
                (
                    "po_value_sar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="PO Value (SAR)",
                    ),
                ),
                (
                    "po_value_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="PO Value (USD/EUR)",
                    ),
                ),
                (
                    "advance_payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Advance Payment",
                    ),
                ),
                (
                    "delivery_status",
                    models.TextField(blank=True, verbose_name="Delivery Status"),
                ),
                (
                    "scm",
                    models.CharField(blank=True, max_length=50, verbose_name="SCM"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.procurementsummary",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "serial_number"],
            },
        ),
    ]
