# Generated by Django 6.0.1 on 2026-03-25 09:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_add_procurement_summary"),
        ("projects", "0004_project_estimated_gp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_to_company",
                    models.CharField(max_length=255, verbose_name="Sold To (Company)"),
                ),
                (
                    "sold_to_address",
                    models.TextField(blank=True, verbose_name="Sold To (Address)"),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Delivery Address"),
                ),
                (
                    "attention",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Attention"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=100, verbose_name="Mobile"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "project_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Project Title"
                    ),
                ),
                (
                    "leap_po_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="LEAP PO No."
                    ),
                ),
                (
                    "client_po_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Client PO No."
                    ),
                ),
                (
                    "dn_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="DN Number / No of Packages",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_delivery_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_notes",
                        to="projects.project",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_notes",
                        to="procurement.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Note",
                "verbose_name_plural": "Delivery Notes",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryNoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(default=1, verbose_name="S.No."),
                ),
                (
                    "make_part_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Make/Part Number"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=12,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "uom",
                    models.CharField(default="Each", max_length=50, verbose_name="UOM"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, verbose_name="Remarks / LNA PO# ref"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "delivery_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.deliverynote",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "serial_number"],
            },
        ),
    ]
