# Generated by Django 6.0.1 on 2026-03-26 07:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_add_delivery_note"),
        ("projects", "0004_project_estimated_gp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverynoteitem",
            options={
                "ordering": ["order", "serial_number"],
                "verbose_name": "Delivery Note Item",
            },
        ),
        migrations.CreateModel(
            name="InventoryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Report Title"),
                ),
                (
                    "warehouse_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Warehouse / Location"
                    ),
                ),
                (
                    "report_date",
                    models.DateField(auto_now_add=True, verbose_name="Report Date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inventory_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_reports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Report",
                "verbose_name_plural": "Inventory Reports",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(default=1, verbose_name="S.No."),
                ),
                (
                    "item_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Item Code / SKU"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Item Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, max_length=255, verbose_name="Model"),
                ),
                (
                    "make",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Make / Manufacturer"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cctv", "CCTV / Cameras"),
                            ("network", "Network / Switches"),
                            ("telecom", "Telecom / Radio"),
                            ("solar", "Solar / Power"),
                            ("electrical", "Electrical"),
                            ("cables", "Cables / Connectors"),
                            ("tools", "Tools / Equipment"),
                            ("safety", "Safety / PPE"),
                            ("furniture", "Furniture / Appliances"),
                            ("consumables", "Consumables"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("issued", "Issued"),
                            ("damaged", "Damaged"),
                            ("returned", "Returned"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="Each", max_length=50, verbose_name="Unit"
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Qty Received",
                    ),
                ),
                (
                    "quantity_issued",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Qty Issued",
                    ),
                ),
                (
                    "balance_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Balance Qty",
                    ),
                ),
                (
                    "min_stock_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Min Stock Level",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Unit Cost (SAR)",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="TAG / Serial"
                    ),
                ),
                (
                    "rack_location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Rack / Shelf / Bin"
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Received Date"
                    ),
                ),
                (
                    "handover_to",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Handover To"
                    ),
                ),
                (
                    "handover_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Handover Date"
                    ),
                ),
                (
                    "project_ref",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Project"
                    ),
                ),
                (
                    "po_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="PO Reference"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.inventoryreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "ordering": ["order", "serial_number"],
            },
        ),
    ]
