# Generated by Django 6.0.1 on 2026-03-26 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_add_inventory_report"),
        ("projects", "0004_project_estimated_gp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FRCReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Report Title"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_frc_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frc_reports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "FRC / PPE Report",
                "verbose_name_plural": "FRC / PPE Reports",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FRCEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(default=1, verbose_name="Sr."),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="Name"),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Designation"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Project"
                    ),
                ),
                (
                    "shirt_size",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Shirt Size"
                    ),
                ),
                (
                    "shirt_qty",
                    models.PositiveIntegerField(default=0, verbose_name="Shirts"),
                ),
                (
                    "pants_size",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pants Size"
                    ),
                ),
                (
                    "pants_qty",
                    models.PositiveIntegerField(default=0, verbose_name="Pants"),
                ),
                (
                    "safety_glasses",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Safety Glasses"
                    ),
                ),
                (
                    "safety_shoes",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Safety Shoes"
                    ),
                ),
                (
                    "shoes_qty",
                    models.PositiveIntegerField(default=0, verbose_name="Shoes Qty"),
                ),
                (
                    "safety_helmet",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Safety Helmet"
                    ),
                ),
                (
                    "receiving_date",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Receiving Date"
                    ),
                ),
                (
                    "handed_to",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Handed To / Remarks"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="procurement.frcreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "FRC Entry",
                "verbose_name_plural": "FRC Entries",
                "ordering": ["order", "serial_number"],
            },
        ),
    ]
