# Generated by Django 6.0.1 on 2026-03-26 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_add_frc_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FRCInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("shirt", "FRC Shirt"),
                            ("pants", "FRC Pants"),
                            ("shoes", "Safety Shoes"),
                            ("helmet", "Safety Helmet"),
                            ("glasses", "Safety Glasses"),
                            ("gloves", "Safety Gloves"),
                            ("vest", "High-Vis Vest"),
                            ("harness", "Safety Harness"),
                            ("coverall", "Coverall"),
                            ("other", "Other PPE"),
                        ],
                        max_length=20,
                        verbose_name="Item Type",
                    ),
                ),
                (
                    "size",
                    models.CharField(blank=True, max_length=50, verbose_name="Size"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, verbose_name="Color"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Description / Notes"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Supplier"
                    ),
                ),
                (
                    "total_purchased",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Purchased"
                    ),
                ),
                (
                    "total_issued",
                    models.PositiveIntegerField(default=0, verbose_name="Total Issued"),
                ),
                (
                    "damaged_lost",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Damaged / Lost"
                    ),
                ),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Min Stock Level"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Unit Cost (SAR)",
                    ),
                ),
                (
                    "last_restocked",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Restocked"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_frc_inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FRC Inventory Item",
                "verbose_name_plural": "FRC Inventory",
                "ordering": ["item_type", "size"],
                "unique_together": {("item_type", "size", "color")},
            },
        ),
    ]
