# Generated by Django 6.0.1 on 2026-04-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0022_add_vendor_quote"),
        ("procurement", "0006_add_frc_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="selected_terms",
            field=models.ManyToManyField(
                blank=True, related_name="purchase_orders", to="costing.termstemplate"
            ),
        ),
    ]
