# Generated by Django 6.0.1 on 2026-04-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0007_po_selected_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="system",
            field=models.CharField(
                blank=True,
                help_text="e.g. Siren, PAGA, PICS, GSM Repeater, CCTV, UPS — or type a custom value",
                max_length=100,
                verbose_name="System",
            ),
        ),
    ]
