# Generated by Django 6.0.1 on 2026-04-29 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0008_po_system_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procurementsummaryitem",
            name="summary",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="description",
            field=models.CharField(
                blank=True,
                help_text='Short label for what this PO covers (e.g. "Poles (Siren)", "Speakers (PAGA)"). Used as the "Sub Item Description" column in procurement summaries.',
                max_length=255,
                verbose_name="PO Description",
            ),
        ),
        migrations.CreateModel(
            name="POSummaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[("internal", "Internal"), ("external", "External")],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "mta_plan",
                    models.DateField(blank=True, null=True, verbose_name="MTA Plan"),
                ),
                (
                    "mta_forecast",
                    models.DateField(
                        blank=True, null=True, verbose_name="MTA Forecast"
                    ),
                ),
                (
                    "mta_actual",
                    models.DateField(blank=True, null=True, verbose_name="MTA Actual"),
                ),
                (
                    "po_plan",
                    models.DateField(blank=True, null=True, verbose_name="PO Plan"),
                ),
                (
                    "po_forecast",
                    models.DateField(blank=True, null=True, verbose_name="PO Forecast"),
                ),
                (
                    "po_actual",
                    models.DateField(blank=True, null=True, verbose_name="PO Actual"),
                ),
                (
                    "production_plan",
                    models.DateField(
                        blank=True, null=True, verbose_name="Production Plan"
                    ),
                ),
                (
                    "production_forecast",
                    models.DateField(
                        blank=True, null=True, verbose_name="Production Forecast"
                    ),
                ),
                (
                    "production_actual",
                    models.DateField(
                        blank=True, null=True, verbose_name="Production Actual"
                    ),
                ),
                (
                    "fat_plan",
                    models.DateField(blank=True, null=True, verbose_name="FAT Plan"),
                ),
                (
                    "fat_forecast",
                    models.DateField(
                        blank=True, null=True, verbose_name="FAT Forecast"
                    ),
                ),
                (
                    "fat_actual",
                    models.DateField(blank=True, null=True, verbose_name="FAT Actual"),
                ),
                (
                    "delivery_plan",
                    models.DateField(
                        blank=True, null=True, verbose_name="Delivery Plan"
                    ),
                ),
                (
                    "delivery_readiness",
                    models.DateField(
                        blank=True, null=True, verbose_name="Readiness Date"
                    ),
                ),
                (
                    "delivery_forecast",
                    models.DateField(
                        blank=True, null=True, verbose_name="Delivery Forecast"
                    ),
                ),
                (
                    "delivery_actual",
                    models.DateField(
                        blank=True, null=True, verbose_name="Delivery Actual"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_entry",
                        to="procurement.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "PO Summary Entry",
                "verbose_name_plural": "PO Summary Entries",
                "ordering": ["purchase_order__system", "purchase_order__po_number"],
            },
        ),
        migrations.DeleteModel(
            name="ProcurementSummary",
        ),
        migrations.DeleteModel(
            name="ProcurementSummaryItem",
        ),
    ]
