# Generated by Django 6.0.1 on 2026-04-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0009_internal_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posummaryentry",
            name="fat_actual",
        ),
        migrations.RemoveField(
            model_name="posummaryentry",
            name="fat_forecast",
        ),
        migrations.RemoveField(
            model_name="posummaryentry",
            name="fat_plan",
        ),
        migrations.RemoveField(
            model_name="posummaryentry",
            name="mta_actual",
        ),
        migrations.RemoveField(
            model_name="posummaryentry",
            name="mta_forecast",
        ),
        migrations.RemoveField(
            model_name="posummaryentry",
            name="mta_plan",
        ),
        migrations.RemoveField(
            model_name="posummaryentry",
            name="production_actual",
        ),
        migrations.RemoveField(
            model_name="posummaryentry",
            name="production_forecast",
        ),
        migrations.RemoveField(
            model_name="posummaryentry",
            name="production_plan",
        ),
    ]
