# Generated by Django 6.0.1 on 2026-04-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0011_move_system_to_lineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="lead_time",
            field=models.CharField(
                blank=True,
                help_text='e.g. "4-6 weeks from PO & payment", "10-15 days"',
                max_length=255,
                verbose_name="Lead Time",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_terms_text",
            field=models.TextField(
                blank=True,
                help_text='Short payment-terms summary used in procurement reports — e.g. "30% Advance\\n70% upon Delivery". Separate from the longer Terms & Conditions text below.',
                verbose_name="Payment Terms (Summary)",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="warranty",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Standard", "24 Months after delivery", "3 Years"',
                max_length=255,
                verbose_name="Warranty",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="advance_payment_sar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Advance Payment (SAR)",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="delivery_status",
            field=models.TextField(
                blank=True,
                help_text='Free-text status, e.g. "Delivered HO", "Received at LNA 04-12-2025".',
                verbose_name="Delivery Status",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="po_value_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="PO Value (USD/EUR)",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="scm",
            field=models.CharField(
                blank=True,
                help_text="Initials of the SCM team member responsible (e.g. ST, ZH).",
                max_length=10,
                verbose_name="SCM",
            ),
        ),
    ]
