# Generated by Django 6.0.1 on 2026-05-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0025_costingsheet_additional_contacts"),
        ("procurement", "0013_cleanup_bogus_totals_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="source_bom_item",
            field=models.ForeignKey(
                blank=True,
                help_text='If imported from a costing sheet BOM, points back to the source line item — used to mark BOM items "already procured" and to show PO traceability per BOM row.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procured_po_items",
                to="costing.costinglineitem",
            ),
        ),
    ]
