# Generated by Django 6.0.1 on 2026-05-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0014_purchaseorderitem_source_bom_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="ceo_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="CEO Approved At"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="ceo_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ceo_approved_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="coo_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="COO Approved At"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="coo_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coo_approved_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="pm_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="PM Approved At"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="pm_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pm_approved_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="scm_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="SCM Approved At"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="scm_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scm_approved_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
