# Generated by Django 6.0.1 on 2026-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0015_purchaseorder_ceo_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="ceo_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="procurement/po_signatures/ceo/",
                verbose_name="CEO Signature Image",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="coo_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="procurement/po_signatures/coo/",
                verbose_name="COO Signature Image",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="pm_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="procurement/po_signatures/pm/",
                verbose_name="PM Signature Image",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="scm_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="procurement/po_signatures/scm/",
                verbose_name="SCM Signature Image",
            ),
        ),
    ]
