# Generated by Django 6.0.6 on 2026-06-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_deliverynoteitem_source_po_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(choices=[('SAR', 'SAR — Saudi Riyal'), ('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('AED', 'AED — UAE Dirham')], default='SAR', max_length=3, verbose_name='Currency'),
        ),
    ]
