# Generated by Django 6.0.6 on 2026-06-28 12:19

import django.db.models.deletion
import procurement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_purchaseorder_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=procurement.models.quotation_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending extraction'), ('extracted', 'Extracted — awaiting review'), ('failed', 'Extraction failed'), ('converted', 'Converted to PO')], default='pending', max_length=12)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=60)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_imports', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotations', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
