# Generated by Django 6.0.6 on 2026-07-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_quotationimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Vendor for this line (carried over from the finance budget).', max_length=255, verbose_name='Vendor'),
        ),
    ]
