# Generated by Django 6.0.6 on 2026-07-20 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0036_costingsheet_bom_started_at_and_more'),
        ('procurement', '0020_purchaseorderitem_vendor_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POTermOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Edited Content')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_overrides', to='procurement.purchaseorder')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_overrides', to='costing.termstemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_term_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PO Terms Override',
                'verbose_name_plural': 'PO Terms Overrides',
                'unique_together': {('purchase_order', 'template')},
            },
        ),
    ]
