# Generated by Django 6.0.7 on 2026-07-19 10:02

import procurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_purchaseorderitem_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='sold_to_company',
            field=models.CharField(max_length=255, validators=[procurement.models.validate_not_numeric_only], verbose_name='Sold To (Company)'),
        ),
    ]
