# Generated by Django 6.0.6 on 2026-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_potermoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='terms_order',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
