# Generated by Django 6.0.7 on 2026-07-20 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_alter_deliverynote_sold_to_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
