# Generated by Django 6.0.7 on 2026-07-21 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_alter_deliverynote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_address',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Delivery Address'),
        ),
    ]
