# Generated by Django 6.0.6 on 2026-07-26 09:17

import datetime
import django.core.validators
import procurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_purchaseorder_terms_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_address',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='sold_to_company',
            field=models.CharField(max_length=255, validators=[procurement.models.validate_not_numeric_only], verbose_name='Sold To (Company)'),
        ),
    ]
