# Generated by Django 6.0.7 on 2026-07-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_potermoverride'),
        ('procurement', '0023_alter_deliverynote_delivery_address'),
    ]

    operations = [
    ]
