# Generated by Django 6.0.6 on 2026-07-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_alter_deliverynote_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='mr_revision',
            field=models.CharField(blank=True, default='R00', help_text='Material Requisition revision shown in the PO PDF footer, e.g. R00.', max_length=10, verbose_name='MR Revision'),
        ),
    ]
