# Generated by Django 6.0.6 on 2026-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_purchaseorder_mr_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(choices=[('SAR', 'SAR — Saudi Riyal'), ('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('AED', 'AED — UAE Dirham'), ('GBP', 'GBP — British Pound')], default='SAR', max_length=3, verbose_name='Currency'),
        ),
    ]
