# Generated by Django 6.0.6 on 2026-08-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0025_alter_purchaseorder_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='terms_heading_font_pt',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
