# Generated by Django 6.0.7 on 2026-08-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0025_alter_purchaseorder_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_email_log',
            field=models.TextField(blank=True, help_text='Timestamped recprd of when the PO was emailed to the vendor (auto-appended, not user-edited).'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_emailed_at',
            field=models.DateTimeField(blank=True, help_text='When the PO document was last successfully emailed to the vendor.', null=True),
        ),
    ]
