# Generated by Django 6.0.6 on 2026-08-30 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_acknowledged(apps, schema_editor):
    """Move existing rows onto the renamed status.

    Safe because the old value carried no behaviour: nothing branched on it
    beyond picking a badge colour, so no workflow state is being reinterpreted.
    """
    PurchaseOrder = apps.get_model('procurement', 'PurchaseOrder')
    PurchaseOrder.objects.filter(status='acknowledged').update(
        status='client_acknowledged')


def unrename_acknowledged(apps, schema_editor):
    """Reverse, so this migration is not one-way.

    Note the asymmetry: a PO acknowledged AFTER this migration also reverses to
    the old value. That is the only sensible answer — the old schema has no
    other status to put it in.
    """
    PurchaseOrder = apps.get_model('procurement', 'PurchaseOrder')
    PurchaseOrder.objects.filter(status='client_acknowledged').update(
        status='acknowledged')


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0026_purchaseorder_terms_heading_font_pt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='client_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='client_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_acknowledged_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('client_acknowledged', 'Client Acknowledged'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='POStageApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('scm', 'SCM Approval'), ('pm', 'PM Approval'), ('coo', 'COO Approval'), ('ceo', 'CEO Approval')], max_length=8, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_stages_to_approve', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PO stage approver',
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='POStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Required when releasing a Client Acknowledged PO.')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO status change',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RunPython(rename_acknowledged, unrename_acknowledged),
    ]
