# Generated by Django 6.0.7 on 2026-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0028_procurement_project_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('supplier_acknowledged', 'Supplier Acknowledged'), ('client_acknowledged', 'Client Acknowledged'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=25),
        ),
    ]
