# Generated by Django 6.0.6 on 2026-09-20 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0029_alter_purchaseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postageapprover',
            name='signer_name',
            field=models.CharField(blank=True, help_text='Printed under this stage on the purchase order. Blank uses the built-in default.', max_length=120),
        ),
        migrations.AlterField(
            model_name='postageapprover',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_stages_to_approve', to=settings.AUTH_USER_MODEL),
        ),
    ]
