# Generated by Django 6.1.1 on 2026-10-05 10:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0045_costinglineitem_added_at_costinglineitem_added_by_and_more'),
        ('procurement', '0030_po_stage_signer_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetOverrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_remarks', 'Awaiting SCM and PM remarks'), ('awaiting_coo', 'Awaiting COO decision'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved - no longer over budget')], default='awaiting_remarks', max_length=20)),
                ('budget_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('spend_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('over_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('scm_remarks', models.TextField(blank=True)),
                ('scm_remarks_at', models.DateTimeField(blank=True, null=True)),
                ('pm_remarks', models.TextField(blank=True)),
                ('pm_remarks_at', models.DateTimeField(blank=True, null=True)),
                ('decision_remarks', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_overruns', to='costing.costingsheet')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pm_remarks_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_overruns', to='procurement.purchaseorder')),
                ('scm_remarks_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetOverrunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('flagged', 'Flagged as over budget'), ('updated', 'Figures changed'), ('scm_remarks', 'SCM remarks added'), ('pm_remarks', 'PM remarks added'), ('approved', 'Approved by COO'), ('rejected', 'Rejected by COO'), ('resolved', 'No longer over budget')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('over_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('overrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='procurement.budgetoverrun')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BudgetOverrunLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=16)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=16)),
                ('over', models.DecimalField(decimal_places=2, max_digits=16)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrun_lines', to='costing.costinglineitem')),
                ('overrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.budgetoverrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='budgetoverrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_remarks', 'awaiting_coo'])), fields=('purchase_order', 'costing_sheet'), name='one_open_overrun_per_po_and_budget'),
        ),
        migrations.AddConstraint(
            model_name='budgetoverrunline',
            constraint=models.UniqueConstraint(fields=('overrun', 'budget_line'), name='one_row_per_overrun_line'),
        ),
    ]
