# Generated by Django 6.0.6 on 2026-08-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('internal_type', models.CharField(choices=[('View', 'View — heading, not postable'), ('Regular', 'Regular'), ('Receivable', 'Receivable'), ('Payable', 'Payable'), ('Liquidity', 'Liquidity')], default='Regular', max_length=20)),
                ('reporting_code', models.CharField(blank=True, max_length=20)),
                ('reporting_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Cleared instead of deleting, so historic references survive.')),
                ('source_row', models.PositiveIntegerField(blank=True, help_text='Row number in the imported workbook, for tracing issues back.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Nearest ancestor account. Blank for a top-level class.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
