# Generated by Django 6.0.6 on 2026-08-19 08:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('projects', '0014_project_bom_started_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invoice', 'Customer Invoice'), ('bill', 'Vendor Bill')], db_index=True, max_length=10)),
                ('number', models.CharField(db_index=True, help_text="Document number. Imported records keep Zoho's own number.", max_length=50)),
                ('reference', models.CharField(blank=True, help_text='Their reference — a customer PO, or the vendor invoice number.', max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('partial', 'Partly paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('zoho_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_documents', to='projects.project')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Line total before tax.', max_digits=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, help_text='Income account for an invoice, expense/COGS for a bill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='accounting.account')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_document_lines', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('both', 'Customer & Vendor')], default='customer', max_length=10)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('cr_number', models.CharField(blank=True, help_text='Commercial Registration number.', max_length=50, verbose_name='CR number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('zoho_contact_id', models.CharField(blank=True, db_index=True, help_text='Zoho Books contact id, so a re-import updates in place.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_partners', to='accounting.account')),
                ('receivable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_partners', to='accounting.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.partner'),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('JV', 'Journal Voucher'), ('PV', 'Payment Voucher'), ('RV', 'Receipt Voucher')], db_index=True, max_length=2)),
                ('number', models.CharField(db_index=True, help_text="Voucher number. Imported records keep Zoho's own number.", max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('narration', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], db_index=True, default='draft', max_length=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('zoho_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(default='manual', help_text="'manual' or 'zoho' — where this record came from.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_vouchers', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounting.partner')),
                ('project', models.ForeignKey(blank=True, help_text='Optional dimension — lets cost be reported per project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_vouchers', to='projects.project')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='accounting.account')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='accounting.partner')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_voucher_lines', to='projects.project')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.voucher')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('kind', 'number'), name='accounting_document_unique_number_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('voucher_type', 'number'), name='accounting_voucher_unique_number_per_type'),
        ),
    ]
