# Generated by Django 6.0.6 on 2026-08-19 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_document_documentline_partner_document_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='accounting.voucher'),
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_payable_account', models.ForeignKey(blank=True, help_text='Credited by a vendor bill when the partner has no own AP account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_receivable_account', models.ForeignKey(blank=True, help_text='Debited by a customer invoice when the partner has no own AR account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('input_tax_account', models.ForeignKey(blank=True, help_text='VAT paid on purchases.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('output_tax_account', models.ForeignKey(blank=True, help_text='VAT charged on sales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Accounting settings',
                'verbose_name_plural': 'Accounting settings',
            },
        ),
    ]
