# Generated by Django 6.0.6 on 2026-08-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_document_voucher_accountingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('organization_id', models.CharField(blank=True, help_text='Zoho Books → Settings → Organization Profile.', max_length=64)),
                ('accounts_url', models.CharField(default='https://accounts.zoho.com', help_text='Region-specific Zoho accounts host, e.g. https://accounts.zoho.sa', max_length=255)),
                ('api_domain', models.CharField(default='https://www.zohoapis.com', max_length=255)),
                ('refresh_token', models.CharField(blank=True, help_text='Obtained once by exchanging a Self Client code; lasts until revoked.', max_length=512)),
                ('access_token', models.CharField(blank=True, max_length=2048)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zoho credentials',
                'verbose_name_plural': 'Zoho credentials',
            },
        ),
    ]
