# Generated by Django 6.0.6 on 2026-08-23 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_zohocredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoAccountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_account_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('zoho_account_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('zoho_account_name', models.CharField(max_length=255)),
                ('zoho_account_type', models.CharField(blank=True, help_text="Zoho's own type, e.g. income, expense, cash, bank.", max_length=50)),
                ('zoho_parent_name', models.CharField(blank=True, max_length=255)),
                ('zoho_is_active', models.BooleanField(default=True)),
                ('is_ignored', models.BooleanField(default=False, help_text='Deliberately not mapped — keeps it off the worklist without pretending it has a home.')),
                ('note', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='The ERP account this lands in. Blank means it still needs mapping.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zoho_mappings', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Zoho account mapping',
                'ordering': ['zoho_account_code', 'zoho_account_name'],
            },
        ),
    ]
