# Generated by Django 6.0.6 on 2026-07-07 06:10

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0022_employee_work_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(help_text='Access-point MAC (BSSID), lowercase — e.g. a1:b2:c3:d4:e5:f6. Read one per AP with: netsh wlan show interfaces.', max_length=17, unique=True)),
                ('label', models.CharField(blank=True, help_text='e.g. "HO 2nd floor AP"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label', 'bssid'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. hostname or asset tag', max_length=120)),
                ('token', models.CharField(default=attendance.models._gen_token, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_devices', to='hr.employee')),
            ],
            options={
                'ordering': ['employee_id', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('active_minutes', models.PositiveIntegerField(default=0, help_text='Distinct minutes with a counted heartbeat (idle excluded).')),
                ('is_present', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='hr.employee')),
            ],
            options={
                'ordering': ['-date', 'employee_id'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(blank=True, max_length=17)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('counted', models.BooleanField(default=False, help_text='Passed all checks and rolled into the day.')),
                ('reason', models.CharField(blank=True, help_text='Why it did not count: off_network / idle / off_hours.', max_length=40)),
                ('hostname', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='attendance.registereddevice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'created_at'], name='attendance__device__1dcc01_idx')],
            },
        ),
    ]
