# Generated by Django 6.0.6 on 2026-07-08 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('hr', '0023_attendancerecord_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddevice',
            name='asset',
            field=models.ForeignKey(blank=True, help_text="The employee's laptop from the HR asset register.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.asset'),
        ),
        migrations.AddField(
            model_name='registereddevice',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Auto-filled from the selected asset.', max_length=255),
        ),
    ]
