# Generated by Django 6.0.6 on 2026-07-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_registereddevice_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddevice',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, help_text='First successful office check-in — the day auto-attendance activated for this device.', null=True),
        ),
    ]
