# Generated by Django 6.0.7 on 2026-08-05 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0037_vendorquote_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('received_at', models.DateTimeField()),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body_preview', models.TextField(blank=True)),
                ('extracted_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('matched_auto', 'Auto-attached'), ('unmatched', 'Needs review'), ('resolved_manual', 'Resolved manually')], default='unmatched', max_length=20)),
                ('match_reason', models.CharField(blank=True, help_text='Why the matcher matched or skipped this message.', max_length=255)),
                ('attachment_filename', models.CharField(blank=True, max_length=255)),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='vendor_email/attachments/')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_emails', to='costing.costingsheet')),
                ('matched_vendor_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_email', to='costing.vendorquote')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_emails_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
