# Generated by Django 6.0.7 on 2026-08-11 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoremailmessage',
            name='attachment_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VendorEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='vendor_email/attachments/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_attachments', to='vendor_email.vendoremailmessage')),
            ],
        ),
    ]
